tonic::include_proto!("api/api");
// Serde JSON support — auto-generated by `pbjson` under OUT_DIR/api/
// This allows you to use `serde_json::from_str::<ListZoneResponse>()` directly

pub const DESCRIPTOR: &[u8] = tonic::include_file_descriptor_set!("api/proto_descriptor");
