// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/alarm.proto

package api

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuditLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LogId         int64                  `protobuf:"varint,1,opt,name=log_id,json=logId,proto3" json:"log_id,omitempty"`
	AlarmId       int64                  `protobuf:"varint,2,opt,name=alarm_id,json=alarmId,proto3" json:"alarm_id,omitempty"`
	DevEui        string                 `protobuf:"bytes,3,opt,name=dev_eui,json=devEui,proto3" json:"dev_eui,omitempty"`
	ChangeType    string                 `protobuf:"bytes,4,opt,name=change_type,json=changeType,proto3" json:"change_type,omitempty"`
	ChangedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=changed_at,json=changedAt,proto3" json:"changed_at,omitempty"`
	ChangedBy     string                 `protobuf:"bytes,6,opt,name=changed_by,json=changedBy,proto3" json:"changed_by,omitempty"`
	OldValues     string                 `protobuf:"bytes,7,opt,name=old_values,json=oldValues,proto3" json:"old_values,omitempty"`
	NewValues     string                 `protobuf:"bytes,8,opt,name=new_values,json=newValues,proto3" json:"new_values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditLog) Reset() {
	*x = AuditLog{}
	mi := &file_api_alarm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditLog) ProtoMessage() {}

func (x *AuditLog) ProtoReflect() protoreflect.Message {
	mi := &file_api_alarm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditLog.ProtoReflect.Descriptor instead.
func (*AuditLog) Descriptor() ([]byte, []int) {
	return file_api_alarm_proto_rawDescGZIP(), []int{0}
}

func (x *AuditLog) GetLogId() int64 {
	if x != nil {
		return x.LogId
	}
	return 0
}

func (x *AuditLog) GetAlarmId() int64 {
	if x != nil {
		return x.AlarmId
	}
	return 0
}

func (x *AuditLog) GetDevEui() string {
	if x != nil {
		return x.DevEui
	}
	return ""
}

func (x *AuditLog) GetChangeType() string {
	if x != nil {
		return x.ChangeType
	}
	return ""
}

func (x *AuditLog) GetChangedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ChangedAt
	}
	return nil
}

func (x *AuditLog) GetChangedBy() string {
	if x != nil {
		return x.ChangedBy
	}
	return ""
}

func (x *AuditLog) GetOldValues() string {
	if x != nil {
		return x.OldValues
	}
	return ""
}

func (x *AuditLog) GetNewValues() string {
	if x != nil {
		return x.NewValues
	}
	return ""
}

type AlarmAutomation struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AlarmId            int64                  `protobuf:"varint,2,opt,name=alarm_id,proto3" json:"alarm_id,omitempty"`
	ReceiverSensor     string                 `protobuf:"bytes,3,opt,name=receiver_sensor,proto3" json:"receiver_sensor,omitempty"`
	Action             string                 `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
	CreatedAt          string                 `protobuf:"bytes,5,opt,name=created_at,proto3" json:"created_at,omitempty"`
	UpdatedAt          string                 `protobuf:"bytes,6,opt,name=updated_at,proto3" json:"updated_at,omitempty"`
	IsActive           bool                   `protobuf:"varint,7,opt,name=is_active,proto3" json:"is_active,omitempty"`
	UserId             string                 `protobuf:"bytes,8,opt,name=user_id,proto3" json:"user_id,omitempty"`
	ReceiverDeviceType int64                  `protobuf:"varint,9,opt,name=receiver_device_type,proto3" json:"receiver_device_type,omitempty"`
	ReceiverDeviceName string                 `protobuf:"bytes,10,opt,name=receiver_device_name,proto3" json:"receiver_device_name,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AlarmAutomation) Reset() {
	*x = AlarmAutomation{}
	mi := &file_api_alarm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlarmAutomation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlarmAutomation) ProtoMessage() {}

func (x *AlarmAutomation) ProtoReflect() protoreflect.Message {
	mi := &file_api_alarm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlarmAutomation.ProtoReflect.Descriptor instead.
func (*AlarmAutomation) Descriptor() ([]byte, []int) {
	return file_api_alarm_proto_rawDescGZIP(), []int{1}
}

func (x *AlarmAutomation) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AlarmAutomation) GetAlarmId() int64 {
	if x != nil {
		return x.AlarmId
	}
	return 0
}

func (x *AlarmAutomation) GetReceiverSensor() string {
	if x != nil {
		return x.ReceiverSensor
	}
	return ""
}

func (x *AlarmAutomation) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AlarmAutomation) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *AlarmAutomation) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *AlarmAutomation) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *AlarmAutomation) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AlarmAutomation) GetReceiverDeviceType() int64 {
	if x != nil {
		return x.ReceiverDeviceType
	}
	return 0
}

func (x *AlarmAutomation) GetReceiverDeviceName() string {
	if x != nil {
		return x.ReceiverDeviceName
	}
	return ""
}

type GetAlarmAutomationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Gateway ID (HEX encoded).
	AlarmId       int64 `protobuf:"varint,1,opt,name=alarm_id,json=alarmId,proto3" json:"alarm_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAlarmAutomationRequest) Reset() {
	*x = GetAlarmAutomationRequest{}
	mi := &file_api_alarm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAlarmAutomationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlarmAutomationRequest) ProtoMessage() {}

func (x *GetAlarmAutomationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_alarm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlarmAutomationRequest.ProtoReflect.Descriptor instead.
func (*GetAlarmAutomationRequest) Descriptor() ([]byte, []int) {
	return file_api_alarm_proto_rawDescGZIP(), []int{2}
}

func (x *GetAlarmAutomationRequest) GetAlarmId() int64 {
	if x != nil {
		return x.AlarmId
	}
	return 0
}

type DeleteAlarmAutomationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Gateway ID (HEX encoded).
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAlarmAutomationRequest) Reset() {
	*x = DeleteAlarmAutomationRequest{}
	mi := &file_api_alarm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAlarmAutomationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAlarmAutomationRequest) ProtoMessage() {}

func (x *DeleteAlarmAutomationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_alarm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAlarmAutomationRequest.ProtoReflect.Descriptor instead.
func (*DeleteAlarmAutomationRequest) Descriptor() ([]byte, []int) {
	return file_api_alarm_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteAlarmAutomationRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateAlarmAutomationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Gateway ID (HEX encoded).
	Id            int64            `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Automation    *AlarmAutomation `protobuf:"bytes,2,opt,name=automation,proto3" json:"automation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAlarmAutomationRequest) Reset() {
	*x = UpdateAlarmAutomationRequest{}
	mi := &file_api_alarm_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAlarmAutomationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAlarmAutomationRequest) ProtoMessage() {}

func (x *UpdateAlarmAutomationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_alarm_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAlarmAutomationRequest.ProtoReflect.Descriptor instead.
func (*UpdateAlarmAutomationRequest) Descriptor() ([]byte, []int) {
	return file_api_alarm_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateAlarmAutomationRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateAlarmAutomationRequest) GetAutomation() *AlarmAutomation {
	if x != nil {
		return x.Automation
	}
	return nil
}

type GetAlarmAutomationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Gateway ID (HEX encoded).
	Result        []*AlarmAutomation `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAlarmAutomationResponse) Reset() {
	*x = GetAlarmAutomationResponse{}
	mi := &file_api_alarm_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAlarmAutomationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlarmAutomationResponse) ProtoMessage() {}

func (x *GetAlarmAutomationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_alarm_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlarmAutomationResponse.ProtoReflect.Descriptor instead.
func (*GetAlarmAutomationResponse) Descriptor() ([]byte, []int) {
	return file_api_alarm_proto_rawDescGZIP(), []int{5}
}

func (x *GetAlarmAutomationResponse) GetResult() []*AlarmAutomation {
	if x != nil {
		return x.Result
	}
	return nil
}

type ListAlarmAutomationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Gateway ID (HEX encoded).
	AlarmId       int64 `protobuf:"varint,1,opt,name=alarm_id,json=alarmId,proto3" json:"alarm_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAlarmAutomationRequest) Reset() {
	*x = ListAlarmAutomationRequest{}
	mi := &file_api_alarm_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAlarmAutomationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAlarmAutomationRequest) ProtoMessage() {}

func (x *ListAlarmAutomationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_alarm_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAlarmAutomationRequest.ProtoReflect.Descriptor instead.
func (*ListAlarmAutomationRequest) Descriptor() ([]byte, []int) {
	return file_api_alarm_proto_rawDescGZIP(), []int{6}
}

func (x *ListAlarmAutomationRequest) GetAlarmId() int64 {
	if x != nil {
		return x.AlarmId
	}
	return 0
}

type ListAlarmAutomationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Gateway ID (HEX encoded).
	Result        []*AlarmAutomation `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAlarmAutomationResponse) Reset() {
	*x = ListAlarmAutomationResponse{}
	mi := &file_api_alarm_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAlarmAutomationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAlarmAutomationResponse) ProtoMessage() {}

func (x *ListAlarmAutomationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_alarm_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAlarmAutomationResponse.ProtoReflect.Descriptor instead.
func (*ListAlarmAutomationResponse) Descriptor() ([]byte, []int) {
	return file_api_alarm_proto_rawDescGZIP(), []int{7}
}

func (x *ListAlarmAutomationResponse) GetResult() []*AlarmAutomation {
	if x != nil {
		return x.Result
	}
	return nil
}

type CreateAlarmAutomationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Gateway ID (HEX encoded).
	AlarmAutomation *AlarmAutomation `protobuf:"bytes,1,opt,name=alarm_automation,json=alarmAutomation,proto3" json:"alarm_automation,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateAlarmAutomationRequest) Reset() {
	*x = CreateAlarmAutomationRequest{}
	mi := &file_api_alarm_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAlarmAutomationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAlarmAutomationRequest) ProtoMessage() {}

func (x *CreateAlarmAutomationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_alarm_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAlarmAutomationRequest.ProtoReflect.Descriptor instead.
func (*CreateAlarmAutomationRequest) Descriptor() ([]byte, []int) {
	return file_api_alarm_proto_rawDescGZIP(), []int{8}
}

func (x *CreateAlarmAutomationRequest) GetAlarmAutomation() *AlarmAutomation {
	if x != nil {
		return x.AlarmAutomation
	}
	return nil
}

type Alarm struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Alarm id.
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Device EUI (HEX encoded).
	DevEui string `protobuf:"bytes,2,opt,name=dev_eui,json=devEUI,proto3" json:"dev_eui,omitempty"`
	// Condition of alarm
	MinTreshold float32 `protobuf:"fixed32,3,opt,name=min_treshold,json=minTreshold,proto3" json:"min_treshold,omitempty"`
	// Value of alarm
	MaxTreshold       float32                `protobuf:"fixed32,4,opt,name=max_treshold,json=maxTreshold,proto3" json:"max_treshold,omitempty"`
	Sms               bool                   `protobuf:"varint,5,opt,name=sms,proto3" json:"sms,omitempty"`
	Email             bool                   `protobuf:"varint,6,opt,name=email,proto3" json:"email,omitempty"`
	Temperature       bool                   `protobuf:"varint,7,opt,name=temperature,proto3" json:"temperature,omitempty"`
	Humadity          bool                   `protobuf:"varint,8,opt,name=humadity,proto3" json:"humadity,omitempty"`
	Ec                bool                   `protobuf:"varint,9,opt,name=ec,proto3" json:"ec,omitempty"`
	Door              bool                   `protobuf:"varint,10,opt,name=door,proto3" json:"door,omitempty"`
	WLeak             bool                   `protobuf:"varint,11,opt,name=w_leak,proto3" json:"w_leak,omitempty"`
	SubmissionDate    *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=submission_date,proto3" json:"submission_date,omitempty"`
	IpAddress         string                 `protobuf:"bytes,13,opt,name=ip_address,proto3" json:"ip_address,omitempty"`
	IsTimeScheduled   bool                   `protobuf:"varint,14,opt,name=is_time_scheduled,proto3" json:"is_time_scheduled,omitempty"`
	StartTime         float32                `protobuf:"fixed32,15,opt,name=start_time,proto3" json:"start_time,omitempty"`
	EndTime           float32                `protobuf:"fixed32,16,opt,name=end_time,proto3" json:"end_time,omitempty"`
	ZoneCategory      int64                  `protobuf:"varint,17,opt,name=zone_category,proto3" json:"zone_category,omitempty"`
	Notification      bool                   `protobuf:"varint,18,opt,name=notification,proto3" json:"notification,omitempty"`
	AlarmDateTime     []*AlarmDateTime       `protobuf:"bytes,19,rep,name=alarm_date_time,proto3" json:"alarm_date_time,omitempty"`
	Pressure          bool                   `protobuf:"varint,20,opt,name=pressure,proto3" json:"pressure,omitempty"`
	NotificationSound string                 `protobuf:"bytes,21,opt,name=notification_sound,json=notificationSound,proto3" json:"notification_sound,omitempty"`
	UserIds           []string               `protobuf:"bytes,22,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	Distance          bool                   `protobuf:"varint,23,opt,name=distance,proto3" json:"distance,omitempty"`
	Time              int64                  `protobuf:"varint,24,opt,name=time,proto3" json:"time,omitempty"`
	IsActive          bool                   `protobuf:"varint,25,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	DefrostTime       int64                  `protobuf:"varint,26,opt,name=defrost_time,json=defrostTime,proto3" json:"defrost_time,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Alarm) Reset() {
	*x = Alarm{}
	mi := &file_api_alarm_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Alarm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alarm) ProtoMessage() {}

func (x *Alarm) ProtoReflect() protoreflect.Message {
	mi := &file_api_alarm_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Alarm.ProtoReflect.Descriptor instead.
func (*Alarm) Descriptor() ([]byte, []int) {
	return file_api_alarm_proto_rawDescGZIP(), []int{9}
}

func (x *Alarm) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Alarm) GetDevEui() string {
	if x != nil {
		return x.DevEui
	}
	return ""
}

func (x *Alarm) GetMinTreshold() float32 {
	if x != nil {
		return x.MinTreshold
	}
	return 0
}

func (x *Alarm) GetMaxTreshold() float32 {
	if x != nil {
		return x.MaxTreshold
	}
	return 0
}

func (x *Alarm) GetSms() bool {
	if x != nil {
		return x.Sms
	}
	return false
}

func (x *Alarm) GetEmail() bool {
	if x != nil {
		return x.Email
	}
	return false
}

func (x *Alarm) GetTemperature() bool {
	if x != nil {
		return x.Temperature
	}
	return false
}

func (x *Alarm) GetHumadity() bool {
	if x != nil {
		return x.Humadity
	}
	return false
}

func (x *Alarm) GetEc() bool {
	if x != nil {
		return x.Ec
	}
	return false
}

func (x *Alarm) GetDoor() bool {
	if x != nil {
		return x.Door
	}
	return false
}

func (x *Alarm) GetWLeak() bool {
	if x != nil {
		return x.WLeak
	}
	return false
}

func (x *Alarm) GetSubmissionDate() *timestamppb.Timestamp {
	if x != nil {
		return x.SubmissionDate
	}
	return nil
}

func (x *Alarm) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *Alarm) GetIsTimeScheduled() bool {
	if x != nil {
		return x.IsTimeScheduled
	}
	return false
}

func (x *Alarm) GetStartTime() float32 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *Alarm) GetEndTime() float32 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *Alarm) GetZoneCategory() int64 {
	if x != nil {
		return x.ZoneCategory
	}
	return 0
}

func (x *Alarm) GetNotification() bool {
	if x != nil {
		return x.Notification
	}
	return false
}

func (x *Alarm) GetAlarmDateTime() []*AlarmDateTime {
	if x != nil {
		return x.AlarmDateTime
	}
	return nil
}

func (x *Alarm) GetPressure() bool {
	if x != nil {
		return x.Pressure
	}
	return false
}

func (x *Alarm) GetNotificationSound() string {
	if x != nil {
		return x.NotificationSound
	}
	return ""
}

func (x *Alarm) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

func (x *Alarm) GetDistance() bool {
	if x != nil {
		return x.Distance
	}
	return false
}

func (x *Alarm) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *Alarm) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Alarm) GetDefrostTime() int64 {
	if x != nil {
		return x.DefrostTime
	}
	return 0
}

type AlarmDateTime struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AlarmId        int64                  `protobuf:"varint,2,opt,name=alarm_id,proto3" json:"alarm_id,omitempty"`
	AlarmDay       int64                  `protobuf:"varint,3,opt,name=alarm_day,proto3" json:"alarm_day,omitempty"`
	AlarmStartTime float32                `protobuf:"fixed32,4,opt,name=alarm_start_time,proto3" json:"alarm_start_time,omitempty"`
	AlarmEndTime   float32                `protobuf:"fixed32,5,opt,name=alarm_end_time,proto3" json:"alarm_end_time,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AlarmDateTime) Reset() {
	*x = AlarmDateTime{}
	mi := &file_api_alarm_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlarmDateTime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlarmDateTime) ProtoMessage() {}

func (x *AlarmDateTime) ProtoReflect() protoreflect.Message {
	mi := &file_api_alarm_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlarmDateTime.ProtoReflect.Descriptor instead.
func (*AlarmDateTime) Descriptor() ([]byte, []int) {
	return file_api_alarm_proto_rawDescGZIP(), []int{10}
}

func (x *AlarmDateTime) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AlarmDateTime) GetAlarmId() int64 {
	if x != nil {
		return x.AlarmId
	}
	return 0
}

func (x *AlarmDateTime) GetAlarmDay() int64 {
	if x != nil {
		return x.AlarmDay
	}
	return 0
}

func (x *AlarmDateTime) GetAlarmStartTime() float32 {
	if x != nil {
		return x.AlarmStartTime
	}
	return 0
}

func (x *AlarmDateTime) GetAlarmEndTime() float32 {
	if x != nil {
		return x.AlarmEndTime
	}
	return 0
}

type CreateDoorTimeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Alarm id.
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Device EUI (HEX encoded).
	DevEui          string                 `protobuf:"bytes,2,opt,name=dev_eui,json=devEUI,proto3" json:"dev_eui,omitempty"`
	Sms             bool                   `protobuf:"varint,3,opt,name=sms,proto3" json:"sms,omitempty"`
	Email           bool                   `protobuf:"varint,4,opt,name=email,proto3" json:"email,omitempty"`
	Notification    bool                   `protobuf:"varint,5,opt,name=notification,proto3" json:"notification,omitempty"`
	UserId          []string               `protobuf:"bytes,6,rep,name=user_id,proto3" json:"user_id,omitempty"`
	SubmissionDate  *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=submission_date,proto3" json:"submission_date,omitempty"`
	IsActive        bool                   `protobuf:"varint,8,opt,name=is_active,proto3" json:"is_active,omitempty"`
	Time            int64                  `protobuf:"varint,9,opt,name=time,proto3" json:"time,omitempty"`
	OrganizationId  string                 `protobuf:"bytes,10,opt,name=organization_id,proto3" json:"organization_id,omitempty"`
	AlarmDateTime   []*AlarmDateTime       `protobuf:"bytes,11,rep,name=alarm_date_time,proto3" json:"alarm_date_time,omitempty"`
	IsTimeScheduled bool                   `protobuf:"varint,12,opt,name=is_time_scheduled,proto3" json:"is_time_scheduled,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateDoorTimeRequest) Reset() {
	*x = CreateDoorTimeRequest{}
	mi := &file_api_alarm_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDoorTimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDoorTimeRequest) ProtoMessage() {}

func (x *CreateDoorTimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_alarm_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDoorTimeRequest.ProtoReflect.Descriptor instead.
func (*CreateDoorTimeRequest) Descriptor() ([]byte, []int) {
	return file_api_alarm_proto_rawDescGZIP(), []int{11}
}

func (x *CreateDoorTimeRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateDoorTimeRequest) GetDevEui() string {
	if x != nil {
		return x.DevEui
	}
	return ""
}

func (x *CreateDoorTimeRequest) GetSms() bool {
	if x != nil {
		return x.Sms
	}
	return false
}

func (x *CreateDoorTimeRequest) GetEmail() bool {
	if x != nil {
		return x.Email
	}
	return false
}

func (x *CreateDoorTimeRequest) GetNotification() bool {
	if x != nil {
		return x.Notification
	}
	return false
}

func (x *CreateDoorTimeRequest) GetUserId() []string {
	if x != nil {
		return x.UserId
	}
	return nil
}

func (x *CreateDoorTimeRequest) GetSubmissionDate() *timestamppb.Timestamp {
	if x != nil {
		return x.SubmissionDate
	}
	return nil
}

func (x *CreateDoorTimeRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *CreateDoorTimeRequest) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *CreateDoorTimeRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *CreateDoorTimeRequest) GetAlarmDateTime() []*AlarmDateTime {
	if x != nil {
		return x.AlarmDateTime
	}
	return nil
}

func (x *CreateDoorTimeRequest) GetIsTimeScheduled() bool {
	if x != nil {
		return x.IsTimeScheduled
	}
	return false
}

type CreateDoorTimeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Alarm id.
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Device EUI (HEX encoded).
	DevEui         string                 `protobuf:"bytes,2,opt,name=dev_eui,json=devEUI,proto3" json:"dev_eui,omitempty"`
	Sms            bool                   `protobuf:"varint,3,opt,name=sms,proto3" json:"sms,omitempty"`
	Email          bool                   `protobuf:"varint,4,opt,name=email,proto3" json:"email,omitempty"`
	Notification   bool                   `protobuf:"varint,5,opt,name=notification,proto3" json:"notification,omitempty"`
	UserId         []string               `protobuf:"bytes,6,rep,name=user_id,proto3" json:"user_id,omitempty"`
	SubmissionDate *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=submission_date,proto3" json:"submission_date,omitempty"`
	IsActive       bool                   `protobuf:"varint,8,opt,name=is_active,proto3" json:"is_active,omitempty"`
	Time           int64                  `protobuf:"varint,9,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateDoorTimeResponse) Reset() {
	*x = CreateDoorTimeResponse{}
	mi := &file_api_alarm_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDoorTimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDoorTimeResponse) ProtoMessage() {}

func (x *CreateDoorTimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_alarm_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDoorTimeResponse.ProtoReflect.Descriptor instead.
func (*CreateDoorTimeResponse) Descriptor() ([]byte, []int) {
	return file_api_alarm_proto_rawDescGZIP(), []int{12}
}

func (x *CreateDoorTimeResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateDoorTimeResponse) GetDevEui() string {
	if x != nil {
		return x.DevEui
	}
	return ""
}

func (x *CreateDoorTimeResponse) GetSms() bool {
	if x != nil {
		return x.Sms
	}
	return false
}

func (x *CreateDoorTimeResponse) GetEmail() bool {
	if x != nil {
		return x.Email
	}
	return false
}

func (x *CreateDoorTimeResponse) GetNotification() bool {
	if x != nil {
		return x.Notification
	}
	return false
}

func (x *CreateDoorTimeResponse) GetUserId() []string {
	if x != nil {
		return x.UserId
	}
	return nil
}

func (x *CreateDoorTimeResponse) GetSubmissionDate() *timestamppb.Timestamp {
	if x != nil {
		return x.SubmissionDate
	}
	return nil
}

func (x *CreateDoorTimeResponse) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *CreateDoorTimeResponse) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

type CreateAlarmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreateAlarm   []*Alarm               `protobuf:"bytes,1,rep,name=create_alarm,json=createAlarm,proto3" json:"create_alarm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAlarmRequest) Reset() {
	*x = CreateAlarmRequest{}
	mi := &file_api_alarm_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAlarmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAlarmRequest) ProtoMessage() {}

func (x *CreateAlarmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_alarm_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAlarmRequest.ProtoReflect.Descriptor instead.
func (*CreateAlarmRequest) Descriptor() ([]byte, []int) {
	return file_api_alarm_proto_rawDescGZIP(), []int{13}
}

func (x *CreateAlarmRequest) GetCreateAlarm() []*Alarm {
	if x != nil {
		return x.CreateAlarm
	}
	return nil
}

type CreateMultipleAlarmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreateAlarm   []*Alarm               `protobuf:"bytes,1,rep,name=create_alarm,json=createAlarm,proto3" json:"create_alarm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMultipleAlarmRequest) Reset() {
	*x = CreateMultipleAlarmRequest{}
	mi := &file_api_alarm_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMultipleAlarmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMultipleAlarmRequest) ProtoMessage() {}

func (x *CreateMultipleAlarmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_alarm_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMultipleAlarmRequest.ProtoReflect.Descriptor instead.
func (*CreateMultipleAlarmRequest) Descriptor() ([]byte, []int) {
	return file_api_alarm_proto_rawDescGZIP(), []int{14}
}

func (x *CreateMultipleAlarmRequest) GetCreateAlarm() []*Alarm {
	if x != nil {
		return x.CreateAlarm
	}
	return nil
}

type CreateMultipleDoorAlarmRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	CreateAlarm   []*CreateDoorTimeRequest `protobuf:"bytes,1,rep,name=create_alarm,json=createAlarm,proto3" json:"create_alarm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMultipleDoorAlarmRequest) Reset() {
	*x = CreateMultipleDoorAlarmRequest{}
	mi := &file_api_alarm_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMultipleDoorAlarmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMultipleDoorAlarmRequest) ProtoMessage() {}

func (x *CreateMultipleDoorAlarmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_alarm_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMultipleDoorAlarmRequest.ProtoReflect.Descriptor instead.
func (*CreateMultipleDoorAlarmRequest) Descriptor() ([]byte, []int) {
	return file_api_alarm_proto_rawDescGZIP(), []int{15}
}

func (x *CreateMultipleDoorAlarmRequest) GetCreateAlarm() []*CreateDoorTimeRequest {
	if x != nil {
		return x.CreateAlarm
	}
	return nil
}

type CreateAlarmMultipleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alarm         []*Alarm               `protobuf:"bytes,1,rep,name=alarm,proto3" json:"alarm,omitempty"`
	UserIds       []string               `protobuf:"bytes,2,rep,name=userIds,proto3" json:"userIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAlarmMultipleResponse) Reset() {
	*x = CreateAlarmMultipleResponse{}
	mi := &file_api_alarm_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAlarmMultipleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAlarmMultipleResponse) ProtoMessage() {}

func (x *CreateAlarmMultipleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_alarm_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAlarmMultipleResponse.ProtoReflect.Descriptor instead.
func (*CreateAlarmMultipleResponse) Descriptor() ([]byte, []int) {
	return file_api_alarm_proto_rawDescGZIP(), []int{16}
}

func (x *CreateAlarmMultipleResponse) GetAlarm() []*Alarm {
	if x != nil {
		return x.Alarm
	}
	return nil
}

func (x *CreateAlarmMultipleResponse) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type GetAlarmRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Device EUI (HEX encoded).
	AlarmId       string `protobuf:"bytes,1,opt,name=alarm_id,json=alarmID,proto3" json:"alarm_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAlarmRequest) Reset() {
	*x = GetAlarmRequest{}
	mi := &file_api_alarm_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAlarmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlarmRequest) ProtoMessage() {}

func (x *GetAlarmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_alarm_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlarmRequest.ProtoReflect.Descriptor instead.
func (*GetAlarmRequest) Descriptor() ([]byte, []int) {
	return file_api_alarm_proto_rawDescGZIP(), []int{17}
}

func (x *GetAlarmRequest) GetAlarmId() string {
	if x != nil {
		return x.AlarmId
	}
	return ""
}

type GetAlarmResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Alarm object
	Alarm         *Alarm `protobuf:"bytes,1,opt,name=alarm,proto3" json:"alarm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAlarmResponse) Reset() {
	*x = GetAlarmResponse{}
	mi := &file_api_alarm_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAlarmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlarmResponse) ProtoMessage() {}

func (x *GetAlarmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_alarm_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlarmResponse.ProtoReflect.Descriptor instead.
func (*GetAlarmResponse) Descriptor() ([]byte, []int) {
	return file_api_alarm_proto_rawDescGZIP(), []int{18}
}

func (x *GetAlarmResponse) GetAlarm() *Alarm {
	if x != nil {
		return x.Alarm
	}
	return nil
}

type DeleteAlarmRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Alarm Id (HEX encoded).
	AlarmId       []string `protobuf:"bytes,1,rep,name=alarm_id,json=alarmID,proto3" json:"alarm_id,omitempty"`
	IpAddress     string   `protobuf:"bytes,2,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAlarmRequest) Reset() {
	*x = DeleteAlarmRequest{}
	mi := &file_api_alarm_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAlarmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAlarmRequest) ProtoMessage() {}

func (x *DeleteAlarmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_alarm_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAlarmRequest.ProtoReflect.Descriptor instead.
func (*DeleteAlarmRequest) Descriptor() ([]byte, []int) {
	return file_api_alarm_proto_rawDescGZIP(), []int{19}
}

func (x *DeleteAlarmRequest) GetAlarmId() []string {
	if x != nil {
		return x.AlarmId
	}
	return nil
}

func (x *DeleteAlarmRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

type DeleteDoorAlarmRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Alarm Id (HEX encoded).
	AlarmId       []string `protobuf:"bytes,1,rep,name=alarm_id,json=alarmID,proto3" json:"alarm_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDoorAlarmRequest) Reset() {
	*x = DeleteDoorAlarmRequest{}
	mi := &file_api_alarm_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDoorAlarmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDoorAlarmRequest) ProtoMessage() {}

func (x *DeleteDoorAlarmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_alarm_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDoorAlarmRequest.ProtoReflect.Descriptor instead.
func (*DeleteDoorAlarmRequest) Descriptor() ([]byte, []int) {
	return file_api_alarm_proto_rawDescGZIP(), []int{20}
}

func (x *DeleteDoorAlarmRequest) GetAlarmId() []string {
	if x != nil {
		return x.AlarmId
	}
	return nil
}

type ListOrganizationAlarmRequest2 struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,proto3" json:"organization_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListOrganizationAlarmRequest2) Reset() {
	*x = ListOrganizationAlarmRequest2{}
	mi := &file_api_alarm_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrganizationAlarmRequest2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrganizationAlarmRequest2) ProtoMessage() {}

func (x *ListOrganizationAlarmRequest2) ProtoReflect() protoreflect.Message {
	mi := &file_api_alarm_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrganizationAlarmRequest2.ProtoReflect.Descriptor instead.
func (*ListOrganizationAlarmRequest2) Descriptor() ([]byte, []int) {
	return file_api_alarm_proto_rawDescGZIP(), []int{21}
}

func (x *ListOrganizationAlarmRequest2) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

type DeleteMultipleAlarmRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Alarm Id (HEX encoded).
	UserId        []string `protobuf:"bytes,1,rep,name=user_id,json=userIDs,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMultipleAlarmRequest) Reset() {
	*x = DeleteMultipleAlarmRequest{}
	mi := &file_api_alarm_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMultipleAlarmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMultipleAlarmRequest) ProtoMessage() {}

func (x *DeleteMultipleAlarmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_alarm_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMultipleAlarmRequest.ProtoReflect.Descriptor instead.
func (*DeleteMultipleAlarmRequest) Descriptor() ([]byte, []int) {
	return file_api_alarm_proto_rawDescGZIP(), []int{22}
}

func (x *DeleteMultipleAlarmRequest) GetUserId() []string {
	if x != nil {
		return x.UserId
	}
	return nil
}

type DeleteMultipleZoneAlarmRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Alarm Id (HEX encoded).
	ZoneId        []int64 `protobuf:"varint,1,rep,packed,name=zone_id,json=zoneIds,proto3" json:"zone_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMultipleZoneAlarmRequest) Reset() {
	*x = DeleteMultipleZoneAlarmRequest{}
	mi := &file_api_alarm_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMultipleZoneAlarmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMultipleZoneAlarmRequest) ProtoMessage() {}

func (x *DeleteMultipleZoneAlarmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_alarm_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMultipleZoneAlarmRequest.ProtoReflect.Descriptor instead.
func (*DeleteMultipleZoneAlarmRequest) Descriptor() ([]byte, []int) {
	return file_api_alarm_proto_rawDescGZIP(), []int{23}
}

func (x *DeleteMultipleZoneAlarmRequest) GetZoneId() []int64 {
	if x != nil {
		return x.ZoneId
	}
	return nil
}

type DeleteMultipleDevAlarmRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Alarm Id (HEX encoded).
	DevEuis       []string `protobuf:"bytes,1,rep,name=dev_euis,json=devEui,proto3" json:"dev_euis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMultipleDevAlarmRequest) Reset() {
	*x = DeleteMultipleDevAlarmRequest{}
	mi := &file_api_alarm_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMultipleDevAlarmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMultipleDevAlarmRequest) ProtoMessage() {}

func (x *DeleteMultipleDevAlarmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_alarm_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMultipleDevAlarmRequest.ProtoReflect.Descriptor instead.
func (*DeleteMultipleDevAlarmRequest) Descriptor() ([]byte, []int) {
	return file_api_alarm_proto_rawDescGZIP(), []int{24}
}

func (x *DeleteMultipleDevAlarmRequest) GetDevEuis() []string {
	if x != nil {
		return x.DevEuis
	}
	return nil
}

type ListOrganizationAlarmResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Alarm id.
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Device EUI (HEX encoded).
	DevEui string `protobuf:"bytes,2,opt,name=dev_eui,json=devEUI,proto3" json:"dev_eui,omitempty"`
	// Device EUI (HEX encoded).
	DeviceName string `protobuf:"bytes,3,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	// Device EUI (HEX encoded).
	ZoneName string `protobuf:"bytes,4,opt,name=zone_name,json=zoneName,proto3" json:"zone_name,omitempty"`
	// Condition of alarm
	MinTreshold float32 `protobuf:"fixed32,5,opt,name=min_treshold,json=minTreshold,proto3" json:"min_treshold,omitempty"`
	// Value of alarm
	MaxTreshold     float32                `protobuf:"fixed32,6,opt,name=max_treshold,json=maxTreshold,proto3" json:"max_treshold,omitempty"`
	Sms             bool                   `protobuf:"varint,7,opt,name=sms,proto3" json:"sms,omitempty"`
	Email           bool                   `protobuf:"varint,8,opt,name=email,proto3" json:"email,omitempty"`
	Temperature     bool                   `protobuf:"varint,9,opt,name=temperature,proto3" json:"temperature,omitempty"`
	Humadity        bool                   `protobuf:"varint,10,opt,name=humadity,proto3" json:"humadity,omitempty"`
	Ec              bool                   `protobuf:"varint,11,opt,name=ec,proto3" json:"ec,omitempty"`
	Door            bool                   `protobuf:"varint,12,opt,name=door,proto3" json:"door,omitempty"`
	WLeak           bool                   `protobuf:"varint,13,opt,name=w_leak,proto3" json:"w_leak,omitempty"`
	SubmissionDate  *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=submission_date,proto3" json:"submission_date,omitempty"`
	IsTimeScheduled bool                   `protobuf:"varint,15,opt,name=is_time_scheduled,proto3" json:"is_time_scheduled,omitempty"`
	Notification    bool                   `protobuf:"varint,16,opt,name=notification,proto3" json:"notification,omitempty"`
	AlarmDateTime   []*AlarmDateTime       `protobuf:"bytes,17,rep,name=alarm_date_time,proto3" json:"alarm_date_time,omitempty"`
	// Device EUI (HEX encoded).
	Username          string   `protobuf:"bytes,18,opt,name=username,proto3" json:"username,omitempty"`
	IsTimerActive     bool     `protobuf:"varint,19,opt,name=is_timer_active,proto3" json:"is_timer_active,omitempty"`
	TimerValue        int64    `protobuf:"varint,20,opt,name=timer_value,proto3" json:"timer_value,omitempty"`
	Pressure          bool     `protobuf:"varint,21,opt,name=pressure,proto3" json:"pressure,omitempty"`
	NotificationSound string   `protobuf:"bytes,22,opt,name=notification_sound,proto3" json:"notification_sound,omitempty"`
	UserIds           []string `protobuf:"bytes,23,rep,name=user_ids,proto3" json:"user_ids,omitempty"`
	Distance          bool     `protobuf:"varint,24,opt,name=distance,proto3" json:"distance,omitempty"`
	Time              int64    `protobuf:"varint,25,opt,name=time,proto3" json:"time,omitempty"`
	IsActive          bool     `protobuf:"varint,26,opt,name=is_active,proto3" json:"is_active,omitempty"`
	DefrostTime       int64    `protobuf:"varint,27,opt,name=defrost_time,proto3" json:"defrost_time,omitempty"`
	ZoneCategory      int64    `protobuf:"varint,28,opt,name=zone_category,proto3" json:"zone_category,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ListOrganizationAlarmResponse) Reset() {
	*x = ListOrganizationAlarmResponse{}
	mi := &file_api_alarm_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrganizationAlarmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrganizationAlarmResponse) ProtoMessage() {}

func (x *ListOrganizationAlarmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_alarm_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrganizationAlarmResponse.ProtoReflect.Descriptor instead.
func (*ListOrganizationAlarmResponse) Descriptor() ([]byte, []int) {
	return file_api_alarm_proto_rawDescGZIP(), []int{25}
}

func (x *ListOrganizationAlarmResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ListOrganizationAlarmResponse) GetDevEui() string {
	if x != nil {
		return x.DevEui
	}
	return ""
}

func (x *ListOrganizationAlarmResponse) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *ListOrganizationAlarmResponse) GetZoneName() string {
	if x != nil {
		return x.ZoneName
	}
	return ""
}

func (x *ListOrganizationAlarmResponse) GetMinTreshold() float32 {
	if x != nil {
		return x.MinTreshold
	}
	return 0
}

func (x *ListOrganizationAlarmResponse) GetMaxTreshold() float32 {
	if x != nil {
		return x.MaxTreshold
	}
	return 0
}

func (x *ListOrganizationAlarmResponse) GetSms() bool {
	if x != nil {
		return x.Sms
	}
	return false
}

func (x *ListOrganizationAlarmResponse) GetEmail() bool {
	if x != nil {
		return x.Email
	}
	return false
}

func (x *ListOrganizationAlarmResponse) GetTemperature() bool {
	if x != nil {
		return x.Temperature
	}
	return false
}

func (x *ListOrganizationAlarmResponse) GetHumadity() bool {
	if x != nil {
		return x.Humadity
	}
	return false
}

func (x *ListOrganizationAlarmResponse) GetEc() bool {
	if x != nil {
		return x.Ec
	}
	return false
}

func (x *ListOrganizationAlarmResponse) GetDoor() bool {
	if x != nil {
		return x.Door
	}
	return false
}

func (x *ListOrganizationAlarmResponse) GetWLeak() bool {
	if x != nil {
		return x.WLeak
	}
	return false
}

func (x *ListOrganizationAlarmResponse) GetSubmissionDate() *timestamppb.Timestamp {
	if x != nil {
		return x.SubmissionDate
	}
	return nil
}

func (x *ListOrganizationAlarmResponse) GetIsTimeScheduled() bool {
	if x != nil {
		return x.IsTimeScheduled
	}
	return false
}

func (x *ListOrganizationAlarmResponse) GetNotification() bool {
	if x != nil {
		return x.Notification
	}
	return false
}

func (x *ListOrganizationAlarmResponse) GetAlarmDateTime() []*AlarmDateTime {
	if x != nil {
		return x.AlarmDateTime
	}
	return nil
}

func (x *ListOrganizationAlarmResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ListOrganizationAlarmResponse) GetIsTimerActive() bool {
	if x != nil {
		return x.IsTimerActive
	}
	return false
}

func (x *ListOrganizationAlarmResponse) GetTimerValue() int64 {
	if x != nil {
		return x.TimerValue
	}
	return 0
}

func (x *ListOrganizationAlarmResponse) GetPressure() bool {
	if x != nil {
		return x.Pressure
	}
	return false
}

func (x *ListOrganizationAlarmResponse) GetNotificationSound() string {
	if x != nil {
		return x.NotificationSound
	}
	return ""
}

func (x *ListOrganizationAlarmResponse) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

func (x *ListOrganizationAlarmResponse) GetDistance() bool {
	if x != nil {
		return x.Distance
	}
	return false
}

func (x *ListOrganizationAlarmResponse) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *ListOrganizationAlarmResponse) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *ListOrganizationAlarmResponse) GetDefrostTime() int64 {
	if x != nil {
		return x.DefrostTime
	}
	return 0
}

func (x *ListOrganizationAlarmResponse) GetZoneCategory() int64 {
	if x != nil {
		return x.ZoneCategory
	}
	return 0
}

type UpdateAlarmRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Alarm object to update.
	Alarm         *Alarm `protobuf:"bytes,1,opt,name=alarm,proto3" json:"alarm,omitempty"`
	AlarmId       string `protobuf:"bytes,2,opt,name=alarm_id,json=alarmID,proto3" json:"alarm_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAlarmRequest) Reset() {
	*x = UpdateAlarmRequest{}
	mi := &file_api_alarm_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAlarmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAlarmRequest) ProtoMessage() {}

func (x *UpdateAlarmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_alarm_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAlarmRequest.ProtoReflect.Descriptor instead.
func (*UpdateAlarmRequest) Descriptor() ([]byte, []int) {
	return file_api_alarm_proto_rawDescGZIP(), []int{26}
}

func (x *UpdateAlarmRequest) GetAlarm() *Alarm {
	if x != nil {
		return x.Alarm
	}
	return nil
}

func (x *UpdateAlarmRequest) GetAlarmId() string {
	if x != nil {
		return x.AlarmId
	}
	return ""
}

type ListDoorAlarmRequest2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DevEui        string                 `protobuf:"bytes,1,opt,name=dev_eui,json=devEUI,proto3" json:"dev_eui,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDoorAlarmRequest2) Reset() {
	*x = ListDoorAlarmRequest2{}
	mi := &file_api_alarm_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDoorAlarmRequest2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDoorAlarmRequest2) ProtoMessage() {}

func (x *ListDoorAlarmRequest2) ProtoReflect() protoreflect.Message {
	mi := &file_api_alarm_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDoorAlarmRequest2.ProtoReflect.Descriptor instead.
func (*ListDoorAlarmRequest2) Descriptor() ([]byte, []int) {
	return file_api_alarm_proto_rawDescGZIP(), []int{27}
}

func (x *ListDoorAlarmRequest2) GetDevEui() string {
	if x != nil {
		return x.DevEui
	}
	return ""
}

type ListDoorAlarmResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Total number of devices available within the result-set.
	TotalCount int64 `protobuf:"varint,1,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	// Devices within this result-set.
	Result        []*CreateDoorTimeResponse `protobuf:"bytes,2,rep,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDoorAlarmResponse) Reset() {
	*x = ListDoorAlarmResponse{}
	mi := &file_api_alarm_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDoorAlarmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDoorAlarmResponse) ProtoMessage() {}

func (x *ListDoorAlarmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_alarm_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDoorAlarmResponse.ProtoReflect.Descriptor instead.
func (*ListDoorAlarmResponse) Descriptor() ([]byte, []int) {
	return file_api_alarm_proto_rawDescGZIP(), []int{28}
}

func (x *ListDoorAlarmResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListDoorAlarmResponse) GetResult() []*CreateDoorTimeResponse {
	if x != nil {
		return x.Result
	}
	return nil
}

type ListOrganizationAlarmRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Max number of devices to return in the result-set.
	OrganizationId string `protobuf:"bytes,1,opt,name=organization_id,proto3" json:"organization_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListOrganizationAlarmRequest) Reset() {
	*x = ListOrganizationAlarmRequest{}
	mi := &file_api_alarm_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrganizationAlarmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrganizationAlarmRequest) ProtoMessage() {}

func (x *ListOrganizationAlarmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_alarm_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrganizationAlarmRequest.ProtoReflect.Descriptor instead.
func (*ListOrganizationAlarmRequest) Descriptor() ([]byte, []int) {
	return file_api_alarm_proto_rawDescGZIP(), []int{29}
}

func (x *ListOrganizationAlarmRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

type ListOrganizationAlarmResponse2 struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Total number of devices available within the result-set.
	TotalCount    int64                            `protobuf:"varint,1,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Result        []*ListOrganizationAlarmResponse `protobuf:"bytes,2,rep,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrganizationAlarmResponse2) Reset() {
	*x = ListOrganizationAlarmResponse2{}
	mi := &file_api_alarm_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrganizationAlarmResponse2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrganizationAlarmResponse2) ProtoMessage() {}

func (x *ListOrganizationAlarmResponse2) ProtoReflect() protoreflect.Message {
	mi := &file_api_alarm_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrganizationAlarmResponse2.ProtoReflect.Descriptor instead.
func (*ListOrganizationAlarmResponse2) Descriptor() ([]byte, []int) {
	return file_api_alarm_proto_rawDescGZIP(), []int{30}
}

func (x *ListOrganizationAlarmResponse2) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListOrganizationAlarmResponse2) GetResult() []*ListOrganizationAlarmResponse {
	if x != nil {
		return x.Result
	}
	return nil
}

type ListORganizationAlarmResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Total number of devices available within the result-set.
	TotalCount    int64 `protobuf:"varint,1,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListORganizationAlarmResponse) Reset() {
	*x = ListORganizationAlarmResponse{}
	mi := &file_api_alarm_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListORganizationAlarmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListORganizationAlarmResponse) ProtoMessage() {}

func (x *ListORganizationAlarmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_alarm_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListORganizationAlarmResponse.ProtoReflect.Descriptor instead.
func (*ListORganizationAlarmResponse) Descriptor() ([]byte, []int) {
	return file_api_alarm_proto_rawDescGZIP(), []int{31}
}

func (x *ListORganizationAlarmResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type AlarmLogs struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	DevEui string                 `protobuf:"bytes,1,opt,name=dev_eui,json=devEUI,proto3" json:"dev_eui,omitempty"`
	// Condition of alarm
	MinTreshold float32 `protobuf:"fixed32,2,opt,name=min_treshold,json=minTreshold,proto3" json:"min_treshold,omitempty"`
	// Value of alarm
	MaxTreshold    float32                `protobuf:"fixed32,3,opt,name=max_treshold,json=maxTreshold,proto3" json:"max_treshold,omitempty"`
	UserId         string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	IpAddress      string                 `protobuf:"bytes,5,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	IsDeleted      int64                  `protobuf:"varint,6,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
	Temperature    bool                   `protobuf:"varint,7,opt,name=temperature,proto3" json:"temperature,omitempty"`
	Humadity       bool                   `protobuf:"varint,8,opt,name=humadity,proto3" json:"humadity,omitempty"`
	Ec             bool                   `protobuf:"varint,9,opt,name=ec,proto3" json:"ec,omitempty"`
	Door           bool                   `protobuf:"varint,10,opt,name=door,proto3" json:"door,omitempty"`
	WLeak          bool                   `protobuf:"varint,11,opt,name=w_leak,proto3" json:"w_leak,omitempty"`
	Sms            bool                   `protobuf:"varint,12,opt,name=sms,proto3" json:"sms,omitempty"`
	SubmissionDate *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=submission_date,json=submissionDate,proto3" json:"submission_date,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AlarmLogs) Reset() {
	*x = AlarmLogs{}
	mi := &file_api_alarm_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlarmLogs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlarmLogs) ProtoMessage() {}

func (x *AlarmLogs) ProtoReflect() protoreflect.Message {
	mi := &file_api_alarm_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlarmLogs.ProtoReflect.Descriptor instead.
func (*AlarmLogs) Descriptor() ([]byte, []int) {
	return file_api_alarm_proto_rawDescGZIP(), []int{32}
}

func (x *AlarmLogs) GetDevEui() string {
	if x != nil {
		return x.DevEui
	}
	return ""
}

func (x *AlarmLogs) GetMinTreshold() float32 {
	if x != nil {
		return x.MinTreshold
	}
	return 0
}

func (x *AlarmLogs) GetMaxTreshold() float32 {
	if x != nil {
		return x.MaxTreshold
	}
	return 0
}

func (x *AlarmLogs) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AlarmLogs) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *AlarmLogs) GetIsDeleted() int64 {
	if x != nil {
		return x.IsDeleted
	}
	return 0
}

func (x *AlarmLogs) GetTemperature() bool {
	if x != nil {
		return x.Temperature
	}
	return false
}

func (x *AlarmLogs) GetHumadity() bool {
	if x != nil {
		return x.Humadity
	}
	return false
}

func (x *AlarmLogs) GetEc() bool {
	if x != nil {
		return x.Ec
	}
	return false
}

func (x *AlarmLogs) GetDoor() bool {
	if x != nil {
		return x.Door
	}
	return false
}

func (x *AlarmLogs) GetWLeak() bool {
	if x != nil {
		return x.WLeak
	}
	return false
}

func (x *AlarmLogs) GetSms() bool {
	if x != nil {
		return x.Sms
	}
	return false
}

func (x *AlarmLogs) GetSubmissionDate() *timestamppb.Timestamp {
	if x != nil {
		return x.SubmissionDate
	}
	return nil
}

type GetAuditLogsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Device ID
	DevEui        string `protobuf:"bytes,1,opt,name=dev_eui,proto3" json:"dev_eui,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuditLogsRequest) Reset() {
	*x = GetAuditLogsRequest{}
	mi := &file_api_alarm_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuditLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuditLogsRequest) ProtoMessage() {}

func (x *GetAuditLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_alarm_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuditLogsRequest.ProtoReflect.Descriptor instead.
func (*GetAuditLogsRequest) Descriptor() ([]byte, []int) {
	return file_api_alarm_proto_rawDescGZIP(), []int{33}
}

func (x *GetAuditLogsRequest) GetDevEui() string {
	if x != nil {
		return x.DevEui
	}
	return ""
}

type GetAuditLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        []*AuditLog            `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuditLogsResponse) Reset() {
	*x = GetAuditLogsResponse{}
	mi := &file_api_alarm_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuditLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuditLogsResponse) ProtoMessage() {}

func (x *GetAuditLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_alarm_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuditLogsResponse.ProtoReflect.Descriptor instead.
func (*GetAuditLogsResponse) Descriptor() ([]byte, []int) {
	return file_api_alarm_proto_rawDescGZIP(), []int{34}
}

func (x *GetAuditLogsResponse) GetResult() []*AuditLog {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_api_alarm_proto protoreflect.FileDescriptor

const file_api_alarm_proto_rawDesc = "" +
	"\n" +
	"\x0fapi/alarm.proto\x12\x03api\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x8e\x02\n" +
	"\bAuditLog\x12\x15\n" +
	"\x06log_id\x18\x01 \x01(\x03R\x05logId\x12\x19\n" +
	"\balarm_id\x18\x02 \x01(\x03R\aalarmId\x12\x17\n" +
	"\adev_eui\x18\x03 \x01(\tR\x06devEui\x12\x1f\n" +
	"\vchange_type\x18\x04 \x01(\tR\n" +
	"changeType\x129\n" +
	"\n" +
	"changed_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tchangedAt\x12\x1d\n" +
	"\n" +
	"changed_by\x18\x06 \x01(\tR\tchangedBy\x12\x1d\n" +
	"\n" +
	"old_values\x18\a \x01(\tR\toldValues\x12\x1d\n" +
	"\n" +
	"new_values\x18\b \x01(\tR\tnewValues\"\xdf\x02\n" +
	"\x0fAlarmAutomation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\balarm_id\x18\x02 \x01(\x03R\balarm_id\x12(\n" +
	"\x0freceiver_sensor\x18\x03 \x01(\tR\x0freceiver_sensor\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\x12\x1e\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\n" +
	"created_at\x12\x1e\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\n" +
	"updated_at\x12\x1c\n" +
	"\tis_active\x18\a \x01(\bR\tis_active\x12\x18\n" +
	"\auser_id\x18\b \x01(\tR\auser_id\x122\n" +
	"\x14receiver_device_type\x18\t \x01(\x03R\x14receiver_device_type\x122\n" +
	"\x14receiver_device_name\x18\n" +
	" \x01(\tR\x14receiver_device_name\"6\n" +
	"\x19GetAlarmAutomationRequest\x12\x19\n" +
	"\balarm_id\x18\x01 \x01(\x03R\aalarmId\".\n" +
	"\x1cDeleteAlarmAutomationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"d\n" +
	"\x1cUpdateAlarmAutomationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x124\n" +
	"\n" +
	"automation\x18\x02 \x01(\v2\x14.api.AlarmAutomationR\n" +
	"automation\"J\n" +
	"\x1aGetAlarmAutomationResponse\x12,\n" +
	"\x06result\x18\x01 \x03(\v2\x14.api.AlarmAutomationR\x06result\"7\n" +
	"\x1aListAlarmAutomationRequest\x12\x19\n" +
	"\balarm_id\x18\x01 \x01(\x03R\aalarmId\"K\n" +
	"\x1bListAlarmAutomationResponse\x12,\n" +
	"\x06result\x18\x01 \x03(\v2\x14.api.AlarmAutomationR\x06result\"_\n" +
	"\x1cCreateAlarmAutomationRequest\x12?\n" +
	"\x10alarm_automation\x18\x01 \x01(\v2\x14.api.AlarmAutomationR\x0falarmAutomation\"\xc6\x06\n" +
	"\x05Alarm\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\adev_eui\x18\x02 \x01(\tR\x06devEUI\x12!\n" +
	"\fmin_treshold\x18\x03 \x01(\x02R\vminTreshold\x12!\n" +
	"\fmax_treshold\x18\x04 \x01(\x02R\vmaxTreshold\x12\x10\n" +
	"\x03sms\x18\x05 \x01(\bR\x03sms\x12\x14\n" +
	"\x05email\x18\x06 \x01(\bR\x05email\x12 \n" +
	"\vtemperature\x18\a \x01(\bR\vtemperature\x12\x1a\n" +
	"\bhumadity\x18\b \x01(\bR\bhumadity\x12\x0e\n" +
	"\x02ec\x18\t \x01(\bR\x02ec\x12\x12\n" +
	"\x04door\x18\n" +
	" \x01(\bR\x04door\x12\x16\n" +
	"\x06w_leak\x18\v \x01(\bR\x06w_leak\x12D\n" +
	"\x0fsubmission_date\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\x0fsubmission_date\x12\x1e\n" +
	"\n" +
	"ip_address\x18\r \x01(\tR\n" +
	"ip_address\x12,\n" +
	"\x11is_time_scheduled\x18\x0e \x01(\bR\x11is_time_scheduled\x12\x1e\n" +
	"\n" +
	"start_time\x18\x0f \x01(\x02R\n" +
	"start_time\x12\x1a\n" +
	"\bend_time\x18\x10 \x01(\x02R\bend_time\x12$\n" +
	"\rzone_category\x18\x11 \x01(\x03R\rzone_category\x12\"\n" +
	"\fnotification\x18\x12 \x01(\bR\fnotification\x12<\n" +
	"\x0falarm_date_time\x18\x13 \x03(\v2\x12.api.AlarmDateTimeR\x0falarm_date_time\x12\x1a\n" +
	"\bpressure\x18\x14 \x01(\bR\bpressure\x12-\n" +
	"\x12notification_sound\x18\x15 \x01(\tR\x11notificationSound\x12\x19\n" +
	"\buser_ids\x18\x16 \x03(\tR\auserIds\x12\x1a\n" +
	"\bdistance\x18\x17 \x01(\bR\bdistance\x12\x12\n" +
	"\x04time\x18\x18 \x01(\x03R\x04time\x12\x1b\n" +
	"\tis_active\x18\x19 \x01(\bR\bisActive\x12!\n" +
	"\fdefrost_time\x18\x1a \x01(\x03R\vdefrostTime\"\xad\x01\n" +
	"\rAlarmDateTime\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\balarm_id\x18\x02 \x01(\x03R\balarm_id\x12\x1c\n" +
	"\talarm_day\x18\x03 \x01(\x03R\talarm_day\x12*\n" +
	"\x10alarm_start_time\x18\x04 \x01(\x02R\x10alarm_start_time\x12&\n" +
	"\x0ealarm_end_time\x18\x05 \x01(\x02R\x0ealarm_end_time\"\xb4\x03\n" +
	"\x15CreateDoorTimeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\adev_eui\x18\x02 \x01(\tR\x06devEUI\x12\x10\n" +
	"\x03sms\x18\x03 \x01(\bR\x03sms\x12\x14\n" +
	"\x05email\x18\x04 \x01(\bR\x05email\x12\"\n" +
	"\fnotification\x18\x05 \x01(\bR\fnotification\x12\x18\n" +
	"\auser_id\x18\x06 \x03(\tR\auser_id\x12D\n" +
	"\x0fsubmission_date\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x0fsubmission_date\x12\x1c\n" +
	"\tis_active\x18\b \x01(\bR\tis_active\x12\x12\n" +
	"\x04time\x18\t \x01(\x03R\x04time\x12(\n" +
	"\x0forganization_id\x18\n" +
	" \x01(\tR\x0forganization_id\x12<\n" +
	"\x0falarm_date_time\x18\v \x03(\v2\x12.api.AlarmDateTimeR\x0falarm_date_time\x12,\n" +
	"\x11is_time_scheduled\x18\f \x01(\bR\x11is_time_scheduled\"\x9f\x02\n" +
	"\x16CreateDoorTimeResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\adev_eui\x18\x02 \x01(\tR\x06devEUI\x12\x10\n" +
	"\x03sms\x18\x03 \x01(\bR\x03sms\x12\x14\n" +
	"\x05email\x18\x04 \x01(\bR\x05email\x12\"\n" +
	"\fnotification\x18\x05 \x01(\bR\fnotification\x12\x18\n" +
	"\auser_id\x18\x06 \x03(\tR\auser_id\x12D\n" +
	"\x0fsubmission_date\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x0fsubmission_date\x12\x1c\n" +
	"\tis_active\x18\b \x01(\bR\tis_active\x12\x12\n" +
	"\x04time\x18\t \x01(\x03R\x04time\"C\n" +
	"\x12CreateAlarmRequest\x12-\n" +
	"\fcreate_alarm\x18\x01 \x03(\v2\n" +
	".api.AlarmR\vcreateAlarm\"K\n" +
	"\x1aCreateMultipleAlarmRequest\x12-\n" +
	"\fcreate_alarm\x18\x01 \x03(\v2\n" +
	".api.AlarmR\vcreateAlarm\"_\n" +
	"\x1eCreateMultipleDoorAlarmRequest\x12=\n" +
	"\fcreate_alarm\x18\x01 \x03(\v2\x1a.api.CreateDoorTimeRequestR\vcreateAlarm\"Y\n" +
	"\x1bCreateAlarmMultipleResponse\x12 \n" +
	"\x05alarm\x18\x01 \x03(\v2\n" +
	".api.AlarmR\x05alarm\x12\x18\n" +
	"\auserIds\x18\x02 \x03(\tR\auserIds\",\n" +
	"\x0fGetAlarmRequest\x12\x19\n" +
	"\balarm_id\x18\x01 \x01(\tR\aalarmID\"4\n" +
	"\x10GetAlarmResponse\x12 \n" +
	"\x05alarm\x18\x01 \x01(\v2\n" +
	".api.AlarmR\x05alarm\"N\n" +
	"\x12DeleteAlarmRequest\x12\x19\n" +
	"\balarm_id\x18\x01 \x03(\tR\aalarmID\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x02 \x01(\tR\tipAddress\"3\n" +
	"\x16DeleteDoorAlarmRequest\x12\x19\n" +
	"\balarm_id\x18\x01 \x03(\tR\aalarmID\"I\n" +
	"\x1dListOrganizationAlarmRequest2\x12(\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0forganization_id\"6\n" +
	"\x1aDeleteMultipleAlarmRequest\x12\x18\n" +
	"\auser_id\x18\x01 \x03(\tR\auserIDs\":\n" +
	"\x1eDeleteMultipleZoneAlarmRequest\x12\x18\n" +
	"\azone_id\x18\x01 \x03(\x03R\azoneIds\"9\n" +
	"\x1dDeleteMultipleDevAlarmRequest\x12\x18\n" +
	"\bdev_euis\x18\x01 \x03(\tR\x06devEui\"\xac\a\n" +
	"\x1dListOrganizationAlarmResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\adev_eui\x18\x02 \x01(\tR\x06devEUI\x12\x1f\n" +
	"\vdevice_name\x18\x03 \x01(\tR\n" +
	"deviceName\x12\x1b\n" +
	"\tzone_name\x18\x04 \x01(\tR\bzoneName\x12!\n" +
	"\fmin_treshold\x18\x05 \x01(\x02R\vminTreshold\x12!\n" +
	"\fmax_treshold\x18\x06 \x01(\x02R\vmaxTreshold\x12\x10\n" +
	"\x03sms\x18\a \x01(\bR\x03sms\x12\x14\n" +
	"\x05email\x18\b \x01(\bR\x05email\x12 \n" +
	"\vtemperature\x18\t \x01(\bR\vtemperature\x12\x1a\n" +
	"\bhumadity\x18\n" +
	" \x01(\bR\bhumadity\x12\x0e\n" +
	"\x02ec\x18\v \x01(\bR\x02ec\x12\x12\n" +
	"\x04door\x18\f \x01(\bR\x04door\x12\x16\n" +
	"\x06w_leak\x18\r \x01(\bR\x06w_leak\x12D\n" +
	"\x0fsubmission_date\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\x0fsubmission_date\x12,\n" +
	"\x11is_time_scheduled\x18\x0f \x01(\bR\x11is_time_scheduled\x12\"\n" +
	"\fnotification\x18\x10 \x01(\bR\fnotification\x12<\n" +
	"\x0falarm_date_time\x18\x11 \x03(\v2\x12.api.AlarmDateTimeR\x0falarm_date_time\x12\x1a\n" +
	"\busername\x18\x12 \x01(\tR\busername\x12(\n" +
	"\x0fis_timer_active\x18\x13 \x01(\bR\x0fis_timer_active\x12 \n" +
	"\vtimer_value\x18\x14 \x01(\x03R\vtimer_value\x12\x1a\n" +
	"\bpressure\x18\x15 \x01(\bR\bpressure\x12.\n" +
	"\x12notification_sound\x18\x16 \x01(\tR\x12notification_sound\x12\x1a\n" +
	"\buser_ids\x18\x17 \x03(\tR\buser_ids\x12\x1a\n" +
	"\bdistance\x18\x18 \x01(\bR\bdistance\x12\x12\n" +
	"\x04time\x18\x19 \x01(\x03R\x04time\x12\x1c\n" +
	"\tis_active\x18\x1a \x01(\bR\tis_active\x12\"\n" +
	"\fdefrost_time\x18\x1b \x01(\x03R\fdefrost_time\x12$\n" +
	"\rzone_category\x18\x1c \x01(\x03R\rzone_category\"Q\n" +
	"\x12UpdateAlarmRequest\x12 \n" +
	"\x05alarm\x18\x01 \x01(\v2\n" +
	".api.AlarmR\x05alarm\x12\x19\n" +
	"\balarm_id\x18\x02 \x01(\tR\aalarmID\"0\n" +
	"\x15ListDoorAlarmRequest2\x12\x17\n" +
	"\adev_eui\x18\x01 \x01(\tR\x06devEUI\"m\n" +
	"\x15ListDoorAlarmResponse\x12\x1f\n" +
	"\vtotal_count\x18\x01 \x01(\x03R\n" +
	"totalCount\x123\n" +
	"\x06result\x18\x02 \x03(\v2\x1b.api.CreateDoorTimeResponseR\x06result\"H\n" +
	"\x1cListOrganizationAlarmRequest\x12(\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0forganization_id\"}\n" +
	"\x1eListOrganizationAlarmResponse2\x12\x1f\n" +
	"\vtotal_count\x18\x01 \x01(\x03R\n" +
	"totalCount\x12:\n" +
	"\x06result\x18\x02 \x03(\v2\".api.ListOrganizationAlarmResponseR\x06result\"@\n" +
	"\x1dListORganizationAlarmResponse\x12\x1f\n" +
	"\vtotal_count\x18\x01 \x01(\x03R\n" +
	"totalCount\"\x92\x03\n" +
	"\tAlarmLogs\x12\x17\n" +
	"\adev_eui\x18\x01 \x01(\tR\x06devEUI\x12!\n" +
	"\fmin_treshold\x18\x02 \x01(\x02R\vminTreshold\x12!\n" +
	"\fmax_treshold\x18\x03 \x01(\x02R\vmaxTreshold\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x05 \x01(\tR\tipAddress\x12\x1d\n" +
	"\n" +
	"is_deleted\x18\x06 \x01(\x03R\tisDeleted\x12 \n" +
	"\vtemperature\x18\a \x01(\bR\vtemperature\x12\x1a\n" +
	"\bhumadity\x18\b \x01(\bR\bhumadity\x12\x0e\n" +
	"\x02ec\x18\t \x01(\bR\x02ec\x12\x12\n" +
	"\x04door\x18\n" +
	" \x01(\bR\x04door\x12\x16\n" +
	"\x06w_leak\x18\v \x01(\bR\x06w_leak\x12\x10\n" +
	"\x03sms\x18\f \x01(\bR\x03sms\x12C\n" +
	"\x0fsubmission_date\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\x0esubmissionDate\"/\n" +
	"\x13GetAuditLogsRequest\x12\x18\n" +
	"\adev_eui\x18\x01 \x01(\tR\adev_eui\"=\n" +
	"\x14GetAuditLogsResponse\x12%\n" +
	"\x06result\x18\x01 \x03(\v2\r.api.AuditLogR\x06result2\xaf\x10\n" +
	"\fAlarmService\x12P\n" +
	"\x06Create\x12\x17.api.CreateAlarmRequest\x1a\x16.google.protobuf.Empty\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/api/alarm\x12Q\n" +
	"\x03Get\x12\x14.api.GetAlarmRequest\x1a\x15.api.GetAlarmResponse\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/api/alarm/{alarm_id}\x12[\n" +
	"\x06Update\x12\x17.api.UpdateAlarmRequest\x1a\x16.google.protobuf.Empty\" \x82\xd3\xe4\x93\x02\x1a:\x01*\x1a\x15/api/alarm/{alarm_id}\x12W\n" +
	"\x06Delete\x12\x17.api.DeleteAlarmRequest\x1a\x16.google.protobuf.Empty\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/api/alarm/delete\x12\xa1\x01\n" +
	"\x19ListAllOrganizationAlarms\x12\".api.ListOrganizationAlarmRequest2\x1a#.api.ListOrganizationAlarmResponse2\";\x82\xd3\xe4\x93\x025\x123/api/alarm/listOrganizationAlarms/{organization_id}\x12o\n" +
	"\x0eCreateMultiple\x12\x1f.api.CreateMultipleAlarmRequest\x1a\x16.google.protobuf.Empty\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/api/alarm/createMultiple\x12o\n" +
	"\x0eDeleteMultiple\x12\x1f.api.DeleteMultipleAlarmRequest\x1a\x16.google.protobuf.Empty\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/api/alarm/deleteMultiple\x12z\n" +
	"\x12DeleteSensorAlarms\x12\".api.DeleteMultipleDevAlarmRequest\x1a\x16.google.protobuf.Empty\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/api/alarm/deleteSensorAlarms\x12w\n" +
	"\x10DeleteZoneAlarms\x12#.api.DeleteMultipleZoneAlarmRequest\x1a\x16.google.protobuf.Empty\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/api/alarm/deleteZoneAlarms\x12o\n" +
	"\x0eCreateDoorTime\x12\x1a.api.CreateDoorTimeRequest\x1a\x1b.api.CreateDoorTimeResponse\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/api/alarm/createDoorTime\x12u\n" +
	"\x0eListDoorAlarm2\x12\x1a.api.ListDoorAlarmRequest2\x1a\x1a.api.ListDoorAlarmResponse\"+\x82\xd3\xe4\x93\x02%\x12#/api/alarm/listDoorAlarm2/{dev_eui}\x12m\n" +
	"\x0fDeleteDoorAlarm\x12\x1b.api.DeleteDoorAlarmRequest\x1a\x16.google.protobuf.Empty\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/api/alarm/deleteDoorAlarm\x12\x85\x01\n" +
	"\x17CreateMultipleDoorAlarm\x12#.api.CreateMultipleDoorAlarmRequest\x1a\x16.google.protobuf.Empty\"-\x82\xd3\xe4\x93\x02':\x01*\"\"/api/alarm/createMultipleDoorAlarm\x12y\n" +
	"\x15CreateAlarmAutomation\x12!.api.CreateAlarmAutomationRequest\x1a\x16.google.protobuf.Empty\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/api/alarm/alarmAutomation\x12\x84\x01\n" +
	"\x12GetAlarmAutomation\x12\x1e.api.GetAlarmAutomationRequest\x1a\x1f.api.GetAlarmAutomationResponse\"-\x82\xd3\xe4\x93\x02'\x12%/api/alarm/alarmAutomation/{alarm_id}\x12{\n" +
	"\x15DeleteAlarmAutomation\x12!.api.DeleteAlarmAutomationRequest\x1a\x16.google.protobuf.Empty\"'\x82\xd3\xe4\x93\x02!*\x1f/api/alarm/alarmAutomation/{id}\x12~\n" +
	"\x15UpdateAlarmAutomation\x12!.api.UpdateAlarmAutomationRequest\x1a\x16.google.protobuf.Empty\"*\x82\xd3\xe4\x93\x02$:\x01*\x1a\x1f/api/alarm/alarmAutomation/{id}\x12k\n" +
	"\fGetAuditLogs\x12\x18.api.GetAuditLogsRequest\x1a\x19.api.GetAuditLogsResponse\"&\x82\xd3\xe4\x93\x02 \x12\x1e/api/alarm/auditLogs/{dev_eui}B\x90\x01\n" +
	"\x11io.chirpstack.apiB\n" +
	"AlarmProtoP\x01Z.github.com/ibrahimozekici/VapsV4/api/go/v4/api\xaa\x02\x0eChirpstack.Api\xca\x02\x0eChirpstack\\Api\xe2\x02\x1aGPBMetadata\\Chirpstack\\Apib\x06proto3"

var (
	file_api_alarm_proto_rawDescOnce sync.Once
	file_api_alarm_proto_rawDescData []byte
)

func file_api_alarm_proto_rawDescGZIP() []byte {
	file_api_alarm_proto_rawDescOnce.Do(func() {
		file_api_alarm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_alarm_proto_rawDesc), len(file_api_alarm_proto_rawDesc)))
	})
	return file_api_alarm_proto_rawDescData
}

var file_api_alarm_proto_msgTypes = make([]protoimpl.MessageInfo, 35)
var file_api_alarm_proto_goTypes = []any{
	(*AuditLog)(nil),                       // 0: api.AuditLog
	(*AlarmAutomation)(nil),                // 1: api.AlarmAutomation
	(*GetAlarmAutomationRequest)(nil),      // 2: api.GetAlarmAutomationRequest
	(*DeleteAlarmAutomationRequest)(nil),   // 3: api.DeleteAlarmAutomationRequest
	(*UpdateAlarmAutomationRequest)(nil),   // 4: api.UpdateAlarmAutomationRequest
	(*GetAlarmAutomationResponse)(nil),     // 5: api.GetAlarmAutomationResponse
	(*ListAlarmAutomationRequest)(nil),     // 6: api.ListAlarmAutomationRequest
	(*ListAlarmAutomationResponse)(nil),    // 7: api.ListAlarmAutomationResponse
	(*CreateAlarmAutomationRequest)(nil),   // 8: api.CreateAlarmAutomationRequest
	(*Alarm)(nil),                          // 9: api.Alarm
	(*AlarmDateTime)(nil),                  // 10: api.AlarmDateTime
	(*CreateDoorTimeRequest)(nil),          // 11: api.CreateDoorTimeRequest
	(*CreateDoorTimeResponse)(nil),         // 12: api.CreateDoorTimeResponse
	(*CreateAlarmRequest)(nil),             // 13: api.CreateAlarmRequest
	(*CreateMultipleAlarmRequest)(nil),     // 14: api.CreateMultipleAlarmRequest
	(*CreateMultipleDoorAlarmRequest)(nil), // 15: api.CreateMultipleDoorAlarmRequest
	(*CreateAlarmMultipleResponse)(nil),    // 16: api.CreateAlarmMultipleResponse
	(*GetAlarmRequest)(nil),                // 17: api.GetAlarmRequest
	(*GetAlarmResponse)(nil),               // 18: api.GetAlarmResponse
	(*DeleteAlarmRequest)(nil),             // 19: api.DeleteAlarmRequest
	(*DeleteDoorAlarmRequest)(nil),         // 20: api.DeleteDoorAlarmRequest
	(*ListOrganizationAlarmRequest2)(nil),  // 21: api.ListOrganizationAlarmRequest2
	(*DeleteMultipleAlarmRequest)(nil),     // 22: api.DeleteMultipleAlarmRequest
	(*DeleteMultipleZoneAlarmRequest)(nil), // 23: api.DeleteMultipleZoneAlarmRequest
	(*DeleteMultipleDevAlarmRequest)(nil),  // 24: api.DeleteMultipleDevAlarmRequest
	(*ListOrganizationAlarmResponse)(nil),  // 25: api.ListOrganizationAlarmResponse
	(*UpdateAlarmRequest)(nil),             // 26: api.UpdateAlarmRequest
	(*ListDoorAlarmRequest2)(nil),          // 27: api.ListDoorAlarmRequest2
	(*ListDoorAlarmResponse)(nil),          // 28: api.ListDoorAlarmResponse
	(*ListOrganizationAlarmRequest)(nil),   // 29: api.ListOrganizationAlarmRequest
	(*ListOrganizationAlarmResponse2)(nil), // 30: api.ListOrganizationAlarmResponse2
	(*ListORganizationAlarmResponse)(nil),  // 31: api.ListORganizationAlarmResponse
	(*AlarmLogs)(nil),                      // 32: api.AlarmLogs
	(*GetAuditLogsRequest)(nil),            // 33: api.GetAuditLogsRequest
	(*GetAuditLogsResponse)(nil),           // 34: api.GetAuditLogsResponse
	(*timestamppb.Timestamp)(nil),          // 35: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                  // 36: google.protobuf.Empty
}
var file_api_alarm_proto_depIdxs = []int32{
	35, // 0: api.AuditLog.changed_at:type_name -> google.protobuf.Timestamp
	1,  // 1: api.UpdateAlarmAutomationRequest.automation:type_name -> api.AlarmAutomation
	1,  // 2: api.GetAlarmAutomationResponse.result:type_name -> api.AlarmAutomation
	1,  // 3: api.ListAlarmAutomationResponse.result:type_name -> api.AlarmAutomation
	1,  // 4: api.CreateAlarmAutomationRequest.alarm_automation:type_name -> api.AlarmAutomation
	35, // 5: api.Alarm.submission_date:type_name -> google.protobuf.Timestamp
	10, // 6: api.Alarm.alarm_date_time:type_name -> api.AlarmDateTime
	35, // 7: api.CreateDoorTimeRequest.submission_date:type_name -> google.protobuf.Timestamp
	10, // 8: api.CreateDoorTimeRequest.alarm_date_time:type_name -> api.AlarmDateTime
	35, // 9: api.CreateDoorTimeResponse.submission_date:type_name -> google.protobuf.Timestamp
	9,  // 10: api.CreateAlarmRequest.create_alarm:type_name -> api.Alarm
	9,  // 11: api.CreateMultipleAlarmRequest.create_alarm:type_name -> api.Alarm
	11, // 12: api.CreateMultipleDoorAlarmRequest.create_alarm:type_name -> api.CreateDoorTimeRequest
	9,  // 13: api.CreateAlarmMultipleResponse.alarm:type_name -> api.Alarm
	9,  // 14: api.GetAlarmResponse.alarm:type_name -> api.Alarm
	35, // 15: api.ListOrganizationAlarmResponse.submission_date:type_name -> google.protobuf.Timestamp
	10, // 16: api.ListOrganizationAlarmResponse.alarm_date_time:type_name -> api.AlarmDateTime
	9,  // 17: api.UpdateAlarmRequest.alarm:type_name -> api.Alarm
	12, // 18: api.ListDoorAlarmResponse.result:type_name -> api.CreateDoorTimeResponse
	25, // 19: api.ListOrganizationAlarmResponse2.result:type_name -> api.ListOrganizationAlarmResponse
	35, // 20: api.AlarmLogs.submission_date:type_name -> google.protobuf.Timestamp
	0,  // 21: api.GetAuditLogsResponse.result:type_name -> api.AuditLog
	13, // 22: api.AlarmService.Create:input_type -> api.CreateAlarmRequest
	17, // 23: api.AlarmService.Get:input_type -> api.GetAlarmRequest
	26, // 24: api.AlarmService.Update:input_type -> api.UpdateAlarmRequest
	19, // 25: api.AlarmService.Delete:input_type -> api.DeleteAlarmRequest
	21, // 26: api.AlarmService.ListAllOrganizationAlarms:input_type -> api.ListOrganizationAlarmRequest2
	14, // 27: api.AlarmService.CreateMultiple:input_type -> api.CreateMultipleAlarmRequest
	22, // 28: api.AlarmService.DeleteMultiple:input_type -> api.DeleteMultipleAlarmRequest
	24, // 29: api.AlarmService.DeleteSensorAlarms:input_type -> api.DeleteMultipleDevAlarmRequest
	23, // 30: api.AlarmService.DeleteZoneAlarms:input_type -> api.DeleteMultipleZoneAlarmRequest
	11, // 31: api.AlarmService.CreateDoorTime:input_type -> api.CreateDoorTimeRequest
	27, // 32: api.AlarmService.ListDoorAlarm2:input_type -> api.ListDoorAlarmRequest2
	20, // 33: api.AlarmService.DeleteDoorAlarm:input_type -> api.DeleteDoorAlarmRequest
	15, // 34: api.AlarmService.CreateMultipleDoorAlarm:input_type -> api.CreateMultipleDoorAlarmRequest
	8,  // 35: api.AlarmService.CreateAlarmAutomation:input_type -> api.CreateAlarmAutomationRequest
	2,  // 36: api.AlarmService.GetAlarmAutomation:input_type -> api.GetAlarmAutomationRequest
	3,  // 37: api.AlarmService.DeleteAlarmAutomation:input_type -> api.DeleteAlarmAutomationRequest
	4,  // 38: api.AlarmService.UpdateAlarmAutomation:input_type -> api.UpdateAlarmAutomationRequest
	33, // 39: api.AlarmService.GetAuditLogs:input_type -> api.GetAuditLogsRequest
	36, // 40: api.AlarmService.Create:output_type -> google.protobuf.Empty
	18, // 41: api.AlarmService.Get:output_type -> api.GetAlarmResponse
	36, // 42: api.AlarmService.Update:output_type -> google.protobuf.Empty
	36, // 43: api.AlarmService.Delete:output_type -> google.protobuf.Empty
	30, // 44: api.AlarmService.ListAllOrganizationAlarms:output_type -> api.ListOrganizationAlarmResponse2
	36, // 45: api.AlarmService.CreateMultiple:output_type -> google.protobuf.Empty
	36, // 46: api.AlarmService.DeleteMultiple:output_type -> google.protobuf.Empty
	36, // 47: api.AlarmService.DeleteSensorAlarms:output_type -> google.protobuf.Empty
	36, // 48: api.AlarmService.DeleteZoneAlarms:output_type -> google.protobuf.Empty
	12, // 49: api.AlarmService.CreateDoorTime:output_type -> api.CreateDoorTimeResponse
	28, // 50: api.AlarmService.ListDoorAlarm2:output_type -> api.ListDoorAlarmResponse
	36, // 51: api.AlarmService.DeleteDoorAlarm:output_type -> google.protobuf.Empty
	36, // 52: api.AlarmService.CreateMultipleDoorAlarm:output_type -> google.protobuf.Empty
	36, // 53: api.AlarmService.CreateAlarmAutomation:output_type -> google.protobuf.Empty
	5,  // 54: api.AlarmService.GetAlarmAutomation:output_type -> api.GetAlarmAutomationResponse
	36, // 55: api.AlarmService.DeleteAlarmAutomation:output_type -> google.protobuf.Empty
	36, // 56: api.AlarmService.UpdateAlarmAutomation:output_type -> google.protobuf.Empty
	34, // 57: api.AlarmService.GetAuditLogs:output_type -> api.GetAuditLogsResponse
	40, // [40:58] is the sub-list for method output_type
	22, // [22:40] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_api_alarm_proto_init() }
func file_api_alarm_proto_init() {
	if File_api_alarm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_alarm_proto_rawDesc), len(file_api_alarm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   35,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_alarm_proto_goTypes,
		DependencyIndexes: file_api_alarm_proto_depIdxs,
		MessageInfos:      file_api_alarm_proto_msgTypes,
	}.Build()
	File_api_alarm_proto = out.File
	file_api_alarm_proto_goTypes = nil
	file_api_alarm_proto_depIdxs = nil
}
