// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/automation.proto

package api

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Automation struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SenderSensor       string                 `protobuf:"bytes,2,opt,name=sender_sensor,json=senderSensor,proto3" json:"sender_sensor,omitempty"`
	ReceiverSensor     string                 `protobuf:"bytes,3,opt,name=receiver_sensor,json=receiverSensor,proto3" json:"receiver_sensor,omitempty"`
	Condition          string                 `protobuf:"bytes,4,opt,name=condition,proto3" json:"condition,omitempty"`
	Action             string                 `protobuf:"bytes,5,opt,name=action,proto3" json:"action,omitempty"`
	CreatedAt          *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt          *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	UserId             string                 `protobuf:"bytes,8,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TenantId           string                 `protobuf:"bytes,9,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	SenderDeviceType   int64                  `protobuf:"varint,10,opt,name=sender_device_type,json=senderDeviceType,proto3" json:"sender_device_type,omitempty"`
	ReceiverDeviceType int64                  `protobuf:"varint,11,opt,name=receiver_device_type,json=receiverDeviceType,proto3" json:"receiver_device_type,omitempty"`
	SenderDeviceName   string                 `protobuf:"bytes,12,opt,name=sender_device_name,json=senderDeviceName,proto3" json:"sender_device_name,omitempty"`
	ReceiverDeviceName string                 `protobuf:"bytes,13,opt,name=receiver_device_name,json=receiverDeviceName,proto3" json:"receiver_device_name,omitempty"`
	TriggerType        string                 `protobuf:"bytes,14,opt,name=trigger_type,json=triggerType,proto3" json:"trigger_type,omitempty"`
	TriggerTime        *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=trigger_time,json=triggerTime,proto3" json:"trigger_time,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Automation) Reset() {
	*x = Automation{}
	mi := &file_api_automation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Automation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Automation) ProtoMessage() {}

func (x *Automation) ProtoReflect() protoreflect.Message {
	mi := &file_api_automation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Automation.ProtoReflect.Descriptor instead.
func (*Automation) Descriptor() ([]byte, []int) {
	return file_api_automation_proto_rawDescGZIP(), []int{0}
}

func (x *Automation) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Automation) GetSenderSensor() string {
	if x != nil {
		return x.SenderSensor
	}
	return ""
}

func (x *Automation) GetReceiverSensor() string {
	if x != nil {
		return x.ReceiverSensor
	}
	return ""
}

func (x *Automation) GetCondition() string {
	if x != nil {
		return x.Condition
	}
	return ""
}

func (x *Automation) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *Automation) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Automation) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Automation) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Automation) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Automation) GetSenderDeviceType() int64 {
	if x != nil {
		return x.SenderDeviceType
	}
	return 0
}

func (x *Automation) GetReceiverDeviceType() int64 {
	if x != nil {
		return x.ReceiverDeviceType
	}
	return 0
}

func (x *Automation) GetSenderDeviceName() string {
	if x != nil {
		return x.SenderDeviceName
	}
	return ""
}

func (x *Automation) GetReceiverDeviceName() string {
	if x != nil {
		return x.ReceiverDeviceName
	}
	return ""
}

func (x *Automation) GetTriggerType() string {
	if x != nil {
		return x.TriggerType
	}
	return ""
}

func (x *Automation) GetTriggerTime() *timestamppb.Timestamp {
	if x != nil {
		return x.TriggerTime
	}
	return nil
}

type CreateAutomationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Automation    *Automation            `protobuf:"bytes,1,opt,name=automation,proto3" json:"automation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAutomationRequest) Reset() {
	*x = CreateAutomationRequest{}
	mi := &file_api_automation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAutomationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAutomationRequest) ProtoMessage() {}

func (x *CreateAutomationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_automation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAutomationRequest.ProtoReflect.Descriptor instead.
func (*CreateAutomationRequest) Descriptor() ([]byte, []int) {
	return file_api_automation_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAutomationRequest) GetAutomation() *Automation {
	if x != nil {
		return x.Automation
	}
	return nil
}

type CreateAutomationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Automation    *Automation            `protobuf:"bytes,1,opt,name=automation,proto3" json:"automation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAutomationResponse) Reset() {
	*x = CreateAutomationResponse{}
	mi := &file_api_automation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAutomationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAutomationResponse) ProtoMessage() {}

func (x *CreateAutomationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_automation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAutomationResponse.ProtoReflect.Descriptor instead.
func (*CreateAutomationResponse) Descriptor() ([]byte, []int) {
	return file_api_automation_proto_rawDescGZIP(), []int{2}
}

func (x *CreateAutomationResponse) GetAutomation() *Automation {
	if x != nil {
		return x.Automation
	}
	return nil
}

type GetAutomationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAutomationRequest) Reset() {
	*x = GetAutomationRequest{}
	mi := &file_api_automation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAutomationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAutomationRequest) ProtoMessage() {}

func (x *GetAutomationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_automation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAutomationRequest.ProtoReflect.Descriptor instead.
func (*GetAutomationRequest) Descriptor() ([]byte, []int) {
	return file_api_automation_proto_rawDescGZIP(), []int{3}
}

func (x *GetAutomationRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetAutomationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Automation    *Automation            `protobuf:"bytes,1,opt,name=automation,proto3" json:"automation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAutomationResponse) Reset() {
	*x = GetAutomationResponse{}
	mi := &file_api_automation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAutomationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAutomationResponse) ProtoMessage() {}

func (x *GetAutomationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_automation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAutomationResponse.ProtoReflect.Descriptor instead.
func (*GetAutomationResponse) Descriptor() ([]byte, []int) {
	return file_api_automation_proto_rawDescGZIP(), []int{4}
}

func (x *GetAutomationResponse) GetAutomation() *Automation {
	if x != nil {
		return x.Automation
	}
	return nil
}

type ListAutomationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DevEui        string                 `protobuf:"bytes,2,opt,name=dev_eui,json=devEui,proto3" json:"dev_eui,omitempty"`
	TenantId      string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAutomationRequest) Reset() {
	*x = ListAutomationRequest{}
	mi := &file_api_automation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAutomationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAutomationRequest) ProtoMessage() {}

func (x *ListAutomationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_automation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAutomationRequest.ProtoReflect.Descriptor instead.
func (*ListAutomationRequest) Descriptor() ([]byte, []int) {
	return file_api_automation_proto_rawDescGZIP(), []int{5}
}

func (x *ListAutomationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListAutomationRequest) GetDevEui() string {
	if x != nil {
		return x.DevEui
	}
	return ""
}

func (x *ListAutomationRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type ListAutomationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Automations   []*Automation          `protobuf:"bytes,1,rep,name=automations,proto3" json:"automations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAutomationResponse) Reset() {
	*x = ListAutomationResponse{}
	mi := &file_api_automation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAutomationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAutomationResponse) ProtoMessage() {}

func (x *ListAutomationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_automation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAutomationResponse.ProtoReflect.Descriptor instead.
func (*ListAutomationResponse) Descriptor() ([]byte, []int) {
	return file_api_automation_proto_rawDescGZIP(), []int{6}
}

func (x *ListAutomationResponse) GetAutomations() []*Automation {
	if x != nil {
		return x.Automations
	}
	return nil
}

type UpdateAutomationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Automation    *Automation            `protobuf:"bytes,1,opt,name=automation,proto3" json:"automation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAutomationRequest) Reset() {
	*x = UpdateAutomationRequest{}
	mi := &file_api_automation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAutomationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAutomationRequest) ProtoMessage() {}

func (x *UpdateAutomationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_automation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAutomationRequest.ProtoReflect.Descriptor instead.
func (*UpdateAutomationRequest) Descriptor() ([]byte, []int) {
	return file_api_automation_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateAutomationRequest) GetAutomation() *Automation {
	if x != nil {
		return x.Automation
	}
	return nil
}

type DeleteAutomationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAutomationRequest) Reset() {
	*x = DeleteAutomationRequest{}
	mi := &file_api_automation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAutomationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAutomationRequest) ProtoMessage() {}

func (x *DeleteAutomationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_automation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAutomationRequest.ProtoReflect.Descriptor instead.
func (*DeleteAutomationRequest) Descriptor() ([]byte, []int) {
	return file_api_automation_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteAutomationRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_api_automation_proto protoreflect.FileDescriptor

const file_api_automation_proto_rawDesc = "" +
	"\n" +
	"\x14api/automation.proto\x12\x03api\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xee\x04\n" +
	"\n" +
	"Automation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12#\n" +
	"\rsender_sensor\x18\x02 \x01(\tR\fsenderSensor\x12'\n" +
	"\x0freceiver_sensor\x18\x03 \x01(\tR\x0ereceiverSensor\x12\x1c\n" +
	"\tcondition\x18\x04 \x01(\tR\tcondition\x12\x16\n" +
	"\x06action\x18\x05 \x01(\tR\x06action\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x17\n" +
	"\auser_id\x18\b \x01(\tR\x06userId\x12\x1b\n" +
	"\ttenant_id\x18\t \x01(\tR\btenantId\x12,\n" +
	"\x12sender_device_type\x18\n" +
	" \x01(\x03R\x10senderDeviceType\x120\n" +
	"\x14receiver_device_type\x18\v \x01(\x03R\x12receiverDeviceType\x12,\n" +
	"\x12sender_device_name\x18\f \x01(\tR\x10senderDeviceName\x120\n" +
	"\x14receiver_device_name\x18\r \x01(\tR\x12receiverDeviceName\x12!\n" +
	"\ftrigger_type\x18\x0e \x01(\tR\vtriggerType\x12=\n" +
	"\ftrigger_time\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\vtriggerTime\"J\n" +
	"\x17CreateAutomationRequest\x12/\n" +
	"\n" +
	"automation\x18\x01 \x01(\v2\x0f.api.AutomationR\n" +
	"automation\"K\n" +
	"\x18CreateAutomationResponse\x12/\n" +
	"\n" +
	"automation\x18\x01 \x01(\v2\x0f.api.AutomationR\n" +
	"automation\"&\n" +
	"\x14GetAutomationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"H\n" +
	"\x15GetAutomationResponse\x12/\n" +
	"\n" +
	"automation\x18\x01 \x01(\v2\x0f.api.AutomationR\n" +
	"automation\"f\n" +
	"\x15ListAutomationRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\adev_eui\x18\x02 \x01(\tR\x06devEui\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\"K\n" +
	"\x16ListAutomationResponse\x121\n" +
	"\vautomations\x18\x01 \x03(\v2\x0f.api.AutomationR\vautomations\"J\n" +
	"\x17UpdateAutomationRequest\x12/\n" +
	"\n" +
	"automation\x18\x01 \x01(\v2\x0f.api.AutomationR\n" +
	"automation\")\n" +
	"\x17DeleteAutomationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id2\xfa\x03\n" +
	"\x11AutomationService\x12a\n" +
	"\x06Create\x12\x1c.api.CreateAutomationRequest\x1a\x1d.api.CreateAutomationResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/api/automation\x12Z\n" +
	"\x03Get\x12\x19.api.GetAutomationRequest\x1a\x1a.api.GetAutomationResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/api/automation/{id}\x12X\n" +
	"\x04List\x12\x1a.api.ListAutomationRequest\x1a\x1b.api.ListAutomationResponse\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/api/automation\x12n\n" +
	"\x06Update\x12\x1c.api.UpdateAutomationRequest\x1a\x1a.api.GetAutomationResponse\"*\x82\xd3\xe4\x93\x02$:\x01*\x1a\x1f/api/automation/{automation.id}\x12\\\n" +
	"\x06Delete\x12\x1c.api.DeleteAutomationRequest\x1a\x16.google.protobuf.Empty\"\x1c\x82\xd3\xe4\x93\x02\x16*\x14/api/automation/{id}B\x90\x01\n" +
	"\x11io.chirpstack.apiB\n" +
	"AlarmProtoP\x01Z.github.com/ibrahimozekici/VapsV4/api/go/v4/api\xaa\x02\x0eChirpstack.Api\xca\x02\x0eChirpstack\\Api\xe2\x02\x1aGPBMetadata\\Chirpstack\\Apib\x06proto3"

var (
	file_api_automation_proto_rawDescOnce sync.Once
	file_api_automation_proto_rawDescData []byte
)

func file_api_automation_proto_rawDescGZIP() []byte {
	file_api_automation_proto_rawDescOnce.Do(func() {
		file_api_automation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_automation_proto_rawDesc), len(file_api_automation_proto_rawDesc)))
	})
	return file_api_automation_proto_rawDescData
}

var file_api_automation_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_automation_proto_goTypes = []any{
	(*Automation)(nil),               // 0: api.Automation
	(*CreateAutomationRequest)(nil),  // 1: api.CreateAutomationRequest
	(*CreateAutomationResponse)(nil), // 2: api.CreateAutomationResponse
	(*GetAutomationRequest)(nil),     // 3: api.GetAutomationRequest
	(*GetAutomationResponse)(nil),    // 4: api.GetAutomationResponse
	(*ListAutomationRequest)(nil),    // 5: api.ListAutomationRequest
	(*ListAutomationResponse)(nil),   // 6: api.ListAutomationResponse
	(*UpdateAutomationRequest)(nil),  // 7: api.UpdateAutomationRequest
	(*DeleteAutomationRequest)(nil),  // 8: api.DeleteAutomationRequest
	(*timestamppb.Timestamp)(nil),    // 9: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),            // 10: google.protobuf.Empty
}
var file_api_automation_proto_depIdxs = []int32{
	9,  // 0: api.Automation.created_at:type_name -> google.protobuf.Timestamp
	9,  // 1: api.Automation.updated_at:type_name -> google.protobuf.Timestamp
	9,  // 2: api.Automation.trigger_time:type_name -> google.protobuf.Timestamp
	0,  // 3: api.CreateAutomationRequest.automation:type_name -> api.Automation
	0,  // 4: api.CreateAutomationResponse.automation:type_name -> api.Automation
	0,  // 5: api.GetAutomationResponse.automation:type_name -> api.Automation
	0,  // 6: api.ListAutomationResponse.automations:type_name -> api.Automation
	0,  // 7: api.UpdateAutomationRequest.automation:type_name -> api.Automation
	1,  // 8: api.AutomationService.Create:input_type -> api.CreateAutomationRequest
	3,  // 9: api.AutomationService.Get:input_type -> api.GetAutomationRequest
	5,  // 10: api.AutomationService.List:input_type -> api.ListAutomationRequest
	7,  // 11: api.AutomationService.Update:input_type -> api.UpdateAutomationRequest
	8,  // 12: api.AutomationService.Delete:input_type -> api.DeleteAutomationRequest
	2,  // 13: api.AutomationService.Create:output_type -> api.CreateAutomationResponse
	4,  // 14: api.AutomationService.Get:output_type -> api.GetAutomationResponse
	6,  // 15: api.AutomationService.List:output_type -> api.ListAutomationResponse
	4,  // 16: api.AutomationService.Update:output_type -> api.GetAutomationResponse
	10, // 17: api.AutomationService.Delete:output_type -> google.protobuf.Empty
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_api_automation_proto_init() }
func file_api_automation_proto_init() {
	if File_api_automation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_automation_proto_rawDesc), len(file_api_automation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_automation_proto_goTypes,
		DependencyIndexes: file_api_automation_proto_depIdxs,
		MessageInfos:      file_api_automation_proto_msgTypes,
	}.Build()
	File_api_automation_proto = out.File
	file_api_automation_proto_goTypes = nil
	file_api_automation_proto_depIdxs = nil
}
