// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/notification.proto

package api

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Notification struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Notification Id
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Notification Sender Id
	SenderId int64 `protobuf:"varint,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	// Notification Receiver Id
	ReceiverId []string `protobuf:"bytes,3,rep,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"`
	// Notification Message
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	CategoryId    int64                  `protobuf:"varint,5,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	IsRead        bool                   `protobuf:"varint,6,opt,name=is_read,json=isRead,proto3" json:"is_read,omitempty"`
	SendTime      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=send_time,json=sendTime,proto3" json:"send_time,omitempty"`
	ReadTime      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=read_time,json=readTime,proto3" json:"read_time,omitempty"`
	SenderIp      string                 `protobuf:"bytes,9,opt,name=sender_ip,json=senderIp,proto3" json:"sender_ip,omitempty"`
	ReaderIp      string                 `protobuf:"bytes,10,opt,name=reader_ip,json=readerIp,proto3" json:"reader_ip,omitempty"`
	IsDeleted     bool                   `protobuf:"varint,11,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
	DeleteTime    *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=delete_time,json=deleteTime,proto3" json:"delete_time,omitempty"`
	DevEui        string                 `protobuf:"bytes,13,opt,name=dev_eui,json=devEui,proto3" json:"dev_eui,omitempty"`
	DeviceName    string                 `protobuf:"bytes,14,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notification) Reset() {
	*x = Notification{}
	mi := &file_api_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_api_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification.ProtoReflect.Descriptor instead.
func (*Notification) Descriptor() ([]byte, []int) {
	return file_api_notification_proto_rawDescGZIP(), []int{0}
}

func (x *Notification) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Notification) GetSenderId() int64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *Notification) GetReceiverId() []string {
	if x != nil {
		return x.ReceiverId
	}
	return nil
}

func (x *Notification) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Notification) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *Notification) GetIsRead() bool {
	if x != nil {
		return x.IsRead
	}
	return false
}

func (x *Notification) GetSendTime() *timestamppb.Timestamp {
	if x != nil {
		return x.SendTime
	}
	return nil
}

func (x *Notification) GetReadTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ReadTime
	}
	return nil
}

func (x *Notification) GetSenderIp() string {
	if x != nil {
		return x.SenderIp
	}
	return ""
}

func (x *Notification) GetReaderIp() string {
	if x != nil {
		return x.ReaderIp
	}
	return ""
}

func (x *Notification) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

func (x *Notification) GetDeleteTime() *timestamppb.Timestamp {
	if x != nil {
		return x.DeleteTime
	}
	return nil
}

func (x *Notification) GetDevEui() string {
	if x != nil {
		return x.DevEui
	}
	return ""
}

func (x *Notification) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

type ListNotificationsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Gateway ID (HEX encoded).
	UserId        string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNotificationsRequest) Reset() {
	*x = ListNotificationsRequest{}
	mi := &file_api_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotificationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotificationsRequest) ProtoMessage() {}

func (x *ListNotificationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotificationsRequest.ProtoReflect.Descriptor instead.
func (*ListNotificationsRequest) Descriptor() ([]byte, []int) {
	return file_api_notification_proto_rawDescGZIP(), []int{1}
}

func (x *ListNotificationsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListNotificationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notifications []*Notification        `protobuf:"bytes,1,rep,name=notifications,proto3" json:"notifications,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNotificationsResponse) Reset() {
	*x = ListNotificationsResponse{}
	mi := &file_api_notification_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotificationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotificationsResponse) ProtoMessage() {}

func (x *ListNotificationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_notification_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotificationsResponse.ProtoReflect.Descriptor instead.
func (*ListNotificationsResponse) Descriptor() ([]byte, []int) {
	return file_api_notification_proto_rawDescGZIP(), []int{2}
}

func (x *ListNotificationsResponse) GetNotifications() []*Notification {
	if x != nil {
		return x.Notifications
	}
	return nil
}

type UpdateNotficationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notifications []int64                `protobuf:"varint,1,rep,packed,name=notifications,proto3" json:"notifications,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNotficationRequest) Reset() {
	*x = UpdateNotficationRequest{}
	mi := &file_api_notification_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNotficationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNotficationRequest) ProtoMessage() {}

func (x *UpdateNotficationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_notification_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNotficationRequest.ProtoReflect.Descriptor instead.
func (*UpdateNotficationRequest) Descriptor() ([]byte, []int) {
	return file_api_notification_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateNotficationRequest) GetNotifications() []int64 {
	if x != nil {
		return x.Notifications
	}
	return nil
}

type UpdateNotficationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notification  *Notification          `protobuf:"bytes,1,opt,name=notification,proto3" json:"notification,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNotficationResponse) Reset() {
	*x = UpdateNotficationResponse{}
	mi := &file_api_notification_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNotficationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNotficationResponse) ProtoMessage() {}

func (x *UpdateNotficationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_notification_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNotficationResponse.ProtoReflect.Descriptor instead.
func (*UpdateNotficationResponse) Descriptor() ([]byte, []int) {
	return file_api_notification_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateNotficationResponse) GetNotification() *Notification {
	if x != nil {
		return x.Notification
	}
	return nil
}

type DeleteNotficationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNotficationRequest) Reset() {
	*x = DeleteNotficationRequest{}
	mi := &file_api_notification_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNotficationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNotficationRequest) ProtoMessage() {}

func (x *DeleteNotficationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_notification_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNotficationRequest.ProtoReflect.Descriptor instead.
func (*DeleteNotficationRequest) Descriptor() ([]byte, []int) {
	return file_api_notification_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteNotficationRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_api_notification_proto protoreflect.FileDescriptor

const file_api_notification_proto_rawDesc = "" +
	"\n" +
	"\x16api/notification.proto\x12\x03api\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xf2\x03\n" +
	"\fNotification\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tsender_id\x18\x02 \x01(\x03R\bsenderId\x12\x1f\n" +
	"\vreceiver_id\x18\x03 \x03(\tR\n" +
	"receiverId\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x1f\n" +
	"\vcategory_id\x18\x05 \x01(\x03R\n" +
	"categoryId\x12\x17\n" +
	"\ais_read\x18\x06 \x01(\bR\x06isRead\x127\n" +
	"\tsend_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\bsendTime\x127\n" +
	"\tread_time\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\breadTime\x12\x1b\n" +
	"\tsender_ip\x18\t \x01(\tR\bsenderIp\x12\x1b\n" +
	"\treader_ip\x18\n" +
	" \x01(\tR\breaderIp\x12\x1d\n" +
	"\n" +
	"is_deleted\x18\v \x01(\bR\tisDeleted\x12;\n" +
	"\vdelete_time\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"deleteTime\x12\x17\n" +
	"\adev_eui\x18\r \x01(\tR\x06devEui\x12\x1f\n" +
	"\vdevice_name\x18\x0e \x01(\tR\n" +
	"deviceName\"2\n" +
	"\x18ListNotificationsRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\"T\n" +
	"\x19ListNotificationsResponse\x127\n" +
	"\rnotifications\x18\x01 \x03(\v2\x11.api.NotificationR\rnotifications\"@\n" +
	"\x18UpdateNotficationRequest\x12$\n" +
	"\rnotifications\x18\x01 \x03(\x03R\rnotifications\"R\n" +
	"\x19UpdateNotficationResponse\x125\n" +
	"\fnotification\x18\x01 \x01(\v2\x11.api.NotificationR\fnotification\"*\n" +
	"\x18DeleteNotficationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id2\xcd\x02\n" +
	"\x13NotificationService\x12j\n" +
	"\x04List\x12\x1d.api.ListNotificationsRequest\x1a\x1e.api.ListNotificationsResponse\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/api/notifications/{userId}\x12^\n" +
	"\x06Update\x12\x1d.api.UpdateNotficationRequest\x1a\x16.google.protobuf.Empty\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\x1a\x12/api/notifications\x12j\n" +
	"\x06Delete\x12\x1d.api.DeleteNotficationRequest\x1a\x16.google.protobuf.Empty\")\x82\xd3\xe4\x93\x02#:\x01*\"\x1e/api/notifications/delete/{id}B\x97\x01\n" +
	"\x11io.chirpstack.apiB\x11NotificationProtoP\x01Z.github.com/ibrahimozekici/VapsV4/api/go/v4/api\xaa\x02\x0eChirpstack.Api\xca\x02\x0eChirpstack\\Api\xe2\x02\x1aGPBMetadata\\Chirpstack\\Apib\x06proto3"

var (
	file_api_notification_proto_rawDescOnce sync.Once
	file_api_notification_proto_rawDescData []byte
)

func file_api_notification_proto_rawDescGZIP() []byte {
	file_api_notification_proto_rawDescOnce.Do(func() {
		file_api_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_notification_proto_rawDesc), len(file_api_notification_proto_rawDesc)))
	})
	return file_api_notification_proto_rawDescData
}

var file_api_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_notification_proto_goTypes = []any{
	(*Notification)(nil),              // 0: api.Notification
	(*ListNotificationsRequest)(nil),  // 1: api.ListNotificationsRequest
	(*ListNotificationsResponse)(nil), // 2: api.ListNotificationsResponse
	(*UpdateNotficationRequest)(nil),  // 3: api.UpdateNotficationRequest
	(*UpdateNotficationResponse)(nil), // 4: api.UpdateNotficationResponse
	(*DeleteNotficationRequest)(nil),  // 5: api.DeleteNotficationRequest
	(*timestamppb.Timestamp)(nil),     // 6: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),             // 7: google.protobuf.Empty
}
var file_api_notification_proto_depIdxs = []int32{
	6, // 0: api.Notification.send_time:type_name -> google.protobuf.Timestamp
	6, // 1: api.Notification.read_time:type_name -> google.protobuf.Timestamp
	6, // 2: api.Notification.delete_time:type_name -> google.protobuf.Timestamp
	0, // 3: api.ListNotificationsResponse.notifications:type_name -> api.Notification
	0, // 4: api.UpdateNotficationResponse.notification:type_name -> api.Notification
	1, // 5: api.NotificationService.List:input_type -> api.ListNotificationsRequest
	3, // 6: api.NotificationService.Update:input_type -> api.UpdateNotficationRequest
	5, // 7: api.NotificationService.Delete:input_type -> api.DeleteNotficationRequest
	2, // 8: api.NotificationService.List:output_type -> api.ListNotificationsResponse
	7, // 9: api.NotificationService.Update:output_type -> google.protobuf.Empty
	7, // 10: api.NotificationService.Delete:output_type -> google.protobuf.Empty
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_api_notification_proto_init() }
func file_api_notification_proto_init() {
	if File_api_notification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_notification_proto_rawDesc), len(file_api_notification_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_notification_proto_goTypes,
		DependencyIndexes: file_api_notification_proto_depIdxs,
		MessageInfos:      file_api_notification_proto_msgTypes,
	}.Build()
	File_api_notification_proto = out.File
	file_api_notification_proto_goTypes = nil
	file_api_notification_proto_depIdxs = nil
}
